### ISSUE TITLE
Dictionary usage problem

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#10]
Originally reported by: **Bhairav Shah (Bitbucket: [bhairav](http://bitbucket.org/bhairav), GitHub: [bhairav](http://github.com/bhairav))**

---

Have an issue with getting dictionary values.  Python 2.7.  Sample code:

```
#!python

a = {}
a[1] = "blah"

class MyCmd(cmd.Cmd):
  def do_printdict(self, line):
    global a
    print "a is %s" % a
    val = a[1]
    print "val for 1 is: %s" % val
    val = a[2]
    print "val for 2 is: %s" % val

my_cmd = MyCmd()
my_cmd.cmdloop()

```

If I import the original cmd, I get the following output:

```
#!python

(Cmd) printdict
a is {1: 'blah'}
val for 1 is: blah
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "<stdin>", line 7, in do_printdict
KeyError: 2
```

If I import cmd2, I get the following output:

```
#!python

(Cmd) printdict
a is {1: 'blah'}
val for 1 is: blah
2
```

The original cmd seems to be doing it right, giving the KeyError.  Not sure what is happening with cmd2.

Thanks.

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/10

**Comment by tleonhardt** [comment]
@bhairav
The perror() function in cmd2 is defined like so:
    def perror(self, errmsg, statement=None):
        if self.debug:
            traceback.print_exc()
        print(str(errmsg))

So if debug is set to false (which is the default), the trackback won't print out, only the error message will.  In this case, the whole exception is:
    KeyError: 2
So the "message" associated with the exception is just "2".

We can definitely do a better job adding some context to let the user know that this is an error message so that they know to turn debug on to view the full trackback.

**Comment by tleonhardt** [comment]
Exceptions are now much more obvious when they occur, so this confusion cannot happen.
