### ISSUE TITLE
Please consider the ability to suppress diagnostics output of "set" command

### ISSUE THREAD

**Issue by godzillachan** [python-cmd2/cmd2#1010]
Currently when a Settable's value is changed via "set" or via startup script, there is a small amount of diagnostics output that is always generated regardless of the "quiet" setting.  For example:

> set root '/.more-space'
root - was: '/.space'
now: '/.more-space'

This is somewhat jarring if we use a lot of "set" commands in startup script.  Would you please consider suppressing this output?

**Comment by KyleKing** [comment]
Would a `set ... --quiet` or `set ... --silent` be useful? Particularly for the case of a startup script

**Comment by kmvanbrunt** [comment]
We're looking at a few options for this one.
1. Add option to run startup script silently. I think this one is a must. The startup script is executed using the `run_script` command. In all other cases, a user would be able to redirect the output of `run_script` to /dev/null. I believe startup scripts should have the same option.
2. Add `--silent` flag to `set` command like `alias` and `macro` commands have. I'm not a fan of this option because it will lead to adding similar options to other commands. I'm starting to regret adding this option to the `alias` and `macro` commands.
3. Calling `pfeedback` instead of `poutput` in set. That way if `quiet` is `True`, then no output would display.

In the current version of cmd2, there a few workarounds.
1. Redirect every set command to /dev/null. (e.g. `set my_option True > /dev/null`). This can be tedious if you have a lot of set commands.
2. Place all the set commands in another script which you run in the startup script and redirect to /dev/null. So your startup script would something like:
```
run_script set_commands.txt > /dev/null
```
