### ISSUE TITLE
default_error formatting

### ISSUE THREAD

**Issue by KyleKing** [python-cmd2/cmd2#1022]
The default_error appears to print without style, but I think it should be red

Is this the intended behavior to print without style or is this a bug in how the style is removed in perror? Temporarily I'm overriding the default() method to set apply_style to true

https://github.com/python-cmd2/cmd2/blob/aac467e6eb2557b15170919446b2d9cc8fffabdc/cmd2/cmd2.py#L2519

**Comment by kmvanbrunt** [comment]
`cmd2.Cmd` has 2 error string members which we do not print in red by default.

```Python
# The error that prints when no help information can be found
self.help_error = "No help on {}"

# The error that prints when a non-existent command is run
self.default_error = "{} is not a recognized command, alias, or macro"
```

Since these are custom messages, we did not want to enforce the message or style on developers.
Rather than overriding the methods which print them, it would be easier for you to do the following in your `__init__()` function.

```Python
#  Print these errors in red 
self.help_error = ansi.style_error(self.help_error)
self.default_error = ansi.style_error(self.default_error)
```

**Comment by KyleKing** [comment]
Thanks, tested and that works!
