### ISSUE TITLE
Error parsing arguments with spaces when used as command

### ISSUE THREAD

**Issue by aenima-x** [python-cmd2/cmd2#1028]
I have a command with an string argument that is a json string.
When the command is called inside cmd2 works perfect but when is call as a command from the terminal 

Example:
This works fine
my_app> example_command -d '{"key": "value"}'

but when executed from command line:
#> my_app example_command -d '{"key": "value"}'

example_command: error: unrecognized arguments: value }

I have tried a lot of ways of escaping it and nothing works

**Comment by anselor** [comment]
If I were to guess, bash might be stripping away the single-quotes. Maybe this could work:

```
#> my_app example_command -d \''{"key": "value"}'\'
```

**Comment by kmvanbrunt** [comment]
**cmd2** uses Python's **shlex** library to split the command line into tokens. Specifically we call it like this:
```Python
shlex.split(str_to_split, comments=False, posix=False)
```

Since **cmd2's** parser uses **shlex** we have whatever limitations it has. The syntax you are suggesting would require some custom parsing on your part.

Read the non-POSIX mode [shlex parsing rules](https://docs.python.org/3/library/shlex.html#parsing-rules) to understand what syntaxes won't fit with **cmd2**.

**Comment by aenima-x** [comment]
Ok with the suggestion of @anselor worked, I will use it like that.

I'm migrating from click and with click the other syntax worked ok.

**Comment by aenima-x** [comment]
thanks @anselor I thought I tried that way
