### ISSUE TITLE
Cmd2 Application wide settings file via cmd2 extension.

### ISSUE THREAD

**Issue by jayrod** [python-cmd2/cmd2#1061]
I've been writing a few application-specific configuration file modules in different ways and haven't found something quite elegant enough. Ideally, I'd like to have a cmd2 add in module that took care of adding these configuration issues. It would work like this.

When a cmd2 application starts up you would attempt to load a configuration file (user specified json, toml, ini.. etc) if successful their would be a Cmd.Configuration object available to all of cmd and subcommands and CommandSets via self._cmd.Config.  

My reasoning is that I would like to have CommandSets that are API clients for specific endpoints but each of those endpoints shouldn't be hard coded. But I cant imagine using Settables to hold these configs unless I could read them from a config file at start up in the event a url changed.

**Comment by tleonhardt** [comment]
Settables are really designed for settings you want users to be able to change at runtime.

So far we have left how to implement at-startup configuration to developers and haven't attempted to provide anything to make this easier.  Typically I have seen developers use either command-line arguments via `argparse`, some sort of configuration file (JSON, YAML, ini, etc.), or a combination thereof.

But I'm open to the concept of providing something to make this easier, particularly if it integrates well with CommandSets.  Any solution needs to be completely cross-platform and work well on Windows, Mac, Linux, Python 3.6+, x86, ARM, etc.

**Comment by kmvanbrunt** [comment]
@jayrod Since `CommandSets` already have access to their parent `cmd2` object, what is blocking your application from having a  configuration structure at the top level which all `CommandSets` have access to?

I'm worried a feature like this isn't generic enough to add to the cmd2 framework since applications vary greatly on how they load config settings.

**Comment by jayrod** [comment]
![cmd2](https://user-images.githubusercontent.com/29623/110249124-8fad4b00-7f42-11eb-8f32-3a04e68ecd4e.jpg)


Here's my external plugin implementation. Because I am creating the CommandSet instances and passing them into the cmd2 app constructor I lose the ability for each Commandset to simply call self.config. I fully admit that I could be thinking of this  incorrectly or misunderstanding how inheritance works.. 


Am I doing this correctly?

**Comment by jayrod** [comment]
I could also be easily convinced that Configuration storage is NOT a framework issue but an implementation one. Perhaps I should just look more into how other applications are implementing persistent configurations. 

When I wrote CLI apps pre cmd2 I would first look to a default ini file to load variables, If they were not present or available I made the arguments mandatory. 

like.. if the ini had a 'port' variable that was set to 8080 then each command would automatically assume this is true. But I could override this variable with the cli argument --port. 

I'm trying to implement something similar in my cmd2 apps. I want to load a file if present at app startup that then is available to all my other commandsets. 

I'll write up a quick POC and share it.

**Comment by jayrod** [comment]
https://github.com/jayrod/cmd2-app-poc-plugin

Here is the POC.. 

https://github.com/jayrod/cmd2-app-poc-plugin/blob/main/sample_plugin/src/sample_plugin/fruits.py

This function does indeed show that a global config object is accessible via self._cmd

  def do_really_like_apples(self, _:Statement):
        apple_setting = self._cmd.config['apple'].getboolean('like')

but this is NOT accessible via the __init__. 

Is this by design?

**Comment by kmvanbrunt** [comment]
@jayrod Yes, it is by design. `CommandSets` have a lifecycle and various events occur within this lifecycle.
Refer to the [event handler](https://cmd2.readthedocs.io/en/stable/features/modular_commands.html#event-handlers) documentation for a description of each event.

The `cmd2` object becomes available to the `CommandSet` upon registration (`on_register()`).

Here is a link to the `CommandSet` [code](https://github.com/python-cmd2/cmd2/blob/master/cmd2/command_definition.py) as well so you can see what each event handler does. The class is at the bottom of that file.

**Comment by kmvanbrunt** [comment]
The main reason I advocate for a common config object being implementation-based is because `cmd2` itself has no common configuration settings that aren't already individual class members. Therefore `cmd2` would have this empty `self.config` member.

Another question that arises is, what type of object is `self.config`? Your example makes it a dictionary. Other developers may prefer a `namedtuple` or `dataclass`. I would not want to enforce such a standard from the framework level.

**Comment by jayrod** [comment]
> Another question that arises is, what type of object is self.config? Your example makes it a dictionary. Other developers may prefer a namedtuple or dataclass

I can agree.. Perhaps it's just better to submit an advanced example. Enforcing a standard from the framework is indeed a "bad" thing but looking at all of the different cmd2 implementations there is a lot of rope available to hang one's self ;)
