### ISSUE TITLE
choice_provider is not working properly

### ISSUE THREAD

**Issue by AdityaRajaram** [python-cmd2/cmd2#1062]
from cmd2 import doesn’t supporting  choices_provider

**Comment by kmvanbrunt** [comment]
@AdityaRajaram `choices_provider` is a feature in our 2.0 release which isn't out yet. What version of cmd2 are you using?

Here is a link for [tab completion](https://cmd2.readthedocs.io/en/1.5.0/features/completion.html) documentation in our latest release (1.5.0).

**Comment by tleonhardt** [comment]
@AdityaRajaram You are probably looking for `choices_function` or `choices_method` instead per the [tab completion](https://cmd2.readthedocs.io/en/1.5.0/features/completion.htmlhttps://cmd2.readthedocs.io/en/1.5.0/features/completion.html) documentation for the latest stable version of `cmd2`.

We updated the documentation link on our main GitHub page to point to the docs for the [stable version](https://cmd2.readthedocs.io/en/stable/) instead of the latest version to hopefully help avoid confusion.

Alternatively, if you want to install the last 2.0 pre-release you can [install that directly from GitHub](https://cmd2.readthedocs.io/en/latest/overview/installation.html#install-from-github)
