### ISSUE TITLE
Propagate exception flag

### ISSUE THREAD

**Issue by MrKevinWeiss** [python-cmd2/cmd2#1063]
I would like to know if there is a way that I can propagate an exception instead of catch and print it?

I would expect that this can be some kwarg in the `cmd2.__init__` that would allow for the exceptions to be raised instead of printed.

The use case is more for the `onecmd` functionality.  We have a GUI that uses the some built-in commands like `run_script` and some other custom commands that are only implemented in the `cmd2` based application. The exceptions should be caught and displayed by the GUI rather than hidden in the terminal.

Though this can be dealt with on the application level it, maybe I would not be the only one who wants this as an optional argument to be able to control the exceptions?

**Comment by kmvanbrunt** [comment]
@MrKevinWeiss As you probably saw in `onecmd_plus_hooks()`, cmd2 already has some custom exception handling for those it doesn't print. As an alternative to adding a parameter to `__init__()`, we could add a new cmd2 exception class called `Cmd2PassthroughException` or something similar. You could use this to wrap whatever exception you want. If  `onecmd_plus_hooks()` catches an exception of this type, it will raise it instead of printing it. The question is whether cmd2 should raise the whole `Cmd2PassthroughException` or just what's wrapped within it.

```Python
class Cmd2PassthroughException(Exception):
    """Custom exception class that will be raised instead of printed"""
    def __init__(self, *args, wrapped_ex: BaseException):
        self.wrapped_ex = wrapped_data
        super().__init__(*args)
```

@tleonhardt @anselor What are your thoughts?

**Comment by MrKevinWeiss** [comment]
A sound idea, either the whole `Cmd2PassthroughException` or raising the specific one would work for me.  I suppose I have a very slight preference for the specific exception as then the GUI app would not need to import another exception type.

> As you probably saw in onecmd_plus_hooks(), cmd2 already has some custom exception handling for those it doesn't print.

No I didn't but that is good to know. 👍

**Comment by tleonhardt** [comment]
I like the idea of passing that specific exception type through and then unwrapping it and raising the wrapped exception.

**Comment by kmvanbrunt** [comment]
This is the final exception class.

```Python
class PassThroughException(Exception):
    """
    Normally all unhandled exceptions raised during commands get printed to the user.
    This class is used to wrap an exception that should be raised instead of printed.
    """

    def __init__(self, *args, wrapped_ex: BaseException):
        """
        Initializer for PassThroughException
        :param wrapped_ex: the exception that will be raised
        """
        self.wrapped_ex = wrapped_ex
        super().__init__(*args)
```

**Comment by MrKevinWeiss** [comment]
Thanks guys!
