### ISSUE TITLE
rl_utils trying to load .py as a shared library on PyPy3

### ISSUE THREAD

**Issue by mgorny** [python-cmd2/cmd2#1096]
When trying to run cmd2's tests on PyPy3, I get the following error:

```
pypy3 -m pytest -vv -ra -l
ImportError while loading conftest '/tmp/portage/dev-python/cmd2-1.5.0/work/cmd2-1.5.0/tests/conftest.py'.
tests/conftest.py:23: in <module>
    import cmd2
cmd2/__init__.py:30: in <module>
    from .cmd2 import Cmd
cmd2/cmd2.py:110: in <module>
    from .rl_utils import (
cmd2/rl_utils.py:124: in <module>
    readline_lib = ctypes.CDLL(readline.__file__)
/usr/lib/pypy3.7/lib-python/3/ctypes/__init__.py:366: in __init__
    pypy_dll = _ffi.CDLL(name, mode)
E   OSError: Cannot load library /usr/lib/pypy3.7/lib_pypy/readline.py: /usr/lib/pypy3.7/lib_pypy/readline.py: invalid ELF header
```

Apparently the cause is cmd2/rl_utils.py#L131:

```
readline_lib = ctypes.CDLL(readline.__file__)
```

which assumes that `readline` will be a shared library rather than pure Python module.

**Comment by kmvanbrunt** [comment]
@mgorny I can fix this `OSError`, but you still won't have tab completion support. Currently, cmd2 supports only GNU readline and pyreadline.

cmd2 imports the shared library for GNU readline because Python's [GNU readline wrapper](https://docs.python.org/3/library/readline.html) does not expose all the functions we need for our tab completion and async alert features.

cmd2 will need a bit of code changes to support these same features using PyPy's readline module.

**Comment by mgorny** [comment]
I suppose it's not critical, so as long as tests pass, I'm  good.
