### ISSUE TITLE
api breakage use_ipython vs include_ipy

### ISSUE THREAD

**Issue by laf0rge** [python-cmd2/cmd2#1120]
Daer cmd2 developers,

I'm the author of a python program that uses cmd2.  Users have recently reported breakage as the following commit breaks API compatibility, apparently without any attention to backards or forward compatibility:

```
commit 2397280cad072a27a51f5ec1cc64908039d14bd1
Renamed use_ipython keyword parameter of cmd2.Cmd.__init__() to include_ipy.
```

How are application developers supposed to deal with this?  Check for the cmd2 version at runtime and then call cmd2.Cmd.__init__() with different kwargs?

I appreciate that the new name may be more appropriate than the old one, but changes like this make the life of application developoers using cmd2 definitely harder.  It might be worth considering this for similar future situations.

**Comment by kmvanbrunt** [comment]
Sorry for the inconvenience. `cmd2` recently released version `2.0.0`. There are quite a few backwards-incompatible changes, which is why we increased the `MAJOR` version from 1 to 2.

All breaking changes are documented in the [CHANGELOG](https://github.com/python-cmd2/cmd2/blob/master/CHANGELOG.md).
 
To avoid this in the future, configure your application to use a specific major version.
For example: `install_requires=['cmd2 >= 2, <3']`
