### ISSUE TITLE
Is it possible to highlight the text color when typing?

### ISSUE THREAD

**Issue by dickens88** [python-cmd2/cmd2#1127]
Dear all,

When the user typing at interactive command (by cmd2), can the keywords typed by the user be highlighted? just like in some linux shell terminal.

![image](https://user-images.githubusercontent.com/8390209/122639203-305afb80-d12b-11eb-8383-f746b725ab4f.png)
you can see the keyword `ls` is highlighted and the params after it will has different color. 

but when you run into a python interactive command (by cmd2), the color is gone.

please guide me if there is any way to make it by cmd2 or with some other solutions. many thanks.

**Comment by kmvanbrunt** [comment]
Kali may be using a `readline` init file to color its text.
https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File.html

Try providing an init file to a `cmd2` app using `readline.read_init_file()`.
https://docs.python.org/3/library/readline.html

I can't provide any more support than that since I've never worked with those files.

**Comment by dickens88** [comment]
@kmvanbrunt thank you so much for your reply. it's not a easy work for me, but anyway it's a useful information :)
