### ISSUE TITLE
Cursor breaks when importing pwntools

### ISSUE THREAD

**Issue by A1-exe** [python-cmd2/cmd2#1139]
Importing pwntools causes the cursor to break when using cmd2, and the problem does not occur when I use the traditional cmd class. 

I noticed that when I import pwntools at the top of my script, cmd2 works fine - until I press enter.
Once I press enter the cmd-line sort of breaks, where I can't even use arrow keys anymore.
To test I created the function:

```python3
def do_load(self, args):
    import pwn
```

Sure enough, the cursor breaks as soon as I use the load command. 
Is there something I should enable/disable in cmd2 to fix this problem?

**Comment by kmvanbrunt** [comment]
I'm not familiar with `pwntools`, but I examined the code which runs when you `import pwn`.
First it calls `pwnlib.args.initialize()`. That in turn calls their terminal initializer called `term.init()`.
`term.init()` then calls `can_init()` and here is the key.

The header to that function says:
```Python
def can_init():
    """This function returns True iff stderr is a TTY and we are not inside a
    REPL.  Iff this function returns `True`, a call to :meth:`init` will let
    ``pwnlib`` manage the terminal.
    """
```

Since `cmd2` is a REPL and we do quite a bit with the terminal and GNU readline, you need to get `can_init()` to return `False`.
The terminal features of `pwntools` and `cmd2` will not play nicely together.

Here is a link the actual code for `can_init()`.
https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/term/__init__.py#L24

Notice it returns `False` if running in an interactive Python shell as well as things like IPython. `cmd2` is very similar to those shell environments.

**Comment by A1-exe** [comment]
Thank you for your assistance.
I will use this hackish solution for now:
```python3
sys.modules['jupyter_client._version'] = {}
```
