### ISSUE TITLE
cmd2 has problem to get the file path

### ISSUE THREAD

**Issue by zhouhao27** [python-cmd2/cmd2#1311]
For example:

```python
    doc_parser = cmd2.Cmd2ArgumentParser(description='Add documents')
    doc_parser.add_argument('path', help='Path of the document file or document folder')

    @cmd2.with_argparser(doc_parser)
    @cmd2.with_category(__app_name__)
    def do_add(self, args: argparse.Namespace):

```

When I pass a path like `add /Users/xxx/Projects/AI/gpt-shell/data/user\ manual.pdf`, it says `Error: unrecognized arguments: manual.pdf`

When I pass a path like `add "/Users/xxx/Projects/AI/gpt-shell/data/user\ manual.pdf"`, then I got an `EXCEPTION of type 'FileNotFoundError' occurred with message:` When I try to access the file. 

How cmd2 handle file path normally?

**Comment by kmvanbrunt** [comment]
`cmd2` uses Python's `shlex` module to split a command line into tokens. Since we support Linux, Mac, and Windows, we decided the simplest syntax would be to use non-POSIX mode. You can read about those parsing rules at the following link.

https://docs.python.org/3/library/shlex.html#parsing-rules

In non-POSIX mode, you need to quote strings with spaces and you do not need to escape spaces with a `\`.
Therefore, write your command this way: `add "/Users/xxx/Projects/AI/gpt-shell/data/user manual.pdf"`.

Also, if you want that argument to support tab completion for file paths, set its `completer` as seen in the following code.

```Python
doc_parser.add_argument('path',
                         help='Path of the document file or document folder',
                         completer=cmd2.Cmd.path_complete)
```

Our tab completion functionality will quote paths with spaces for you.

**Comment by zhouhao27** [comment]
Yes. The tab completer works. But dragging a file into terminal doesn't work. Since the format is something like `/Users/zhouhao/Projects/AI/gpt-shell/data/user\ manual.pdf`.

**Comment by kmvanbrunt** [comment]
True, you won't be able to drag files into the terminal if their names contain a space or anything else which produces an escape character.
