### ISSUE TITLE
read_input completer not working

### ISSUE THREAD

**Issue by Sripadvallabh** [python-cmd2/cmd2#1316]
read_input completer doesn't work if spaces are present in the string.

code:
```
~  143     userInput = self.read_input(Fore.CYAN + prompt + Style.RESET_ALL,
+  144                            history=history,
+  145                            completion_mode=cmd2.CompletionMode.CUSTOM,
+  146                            completer=completerFn)
```

With no input, my "HITTING" string of my completer function is printed:
```
(lӓut-leaf2) configure
(leaf2:config)> HITTING
(lӓut-leaf2)
```

With some input without string such as 'abcd', still 'HITTING' is printed
```
(lӓut-leaf2) configure
(leaf2:config)> abcdHITTING
HITTING
```

But with an input containing spaces, the 'HITTING' is not printed after pressing <TAB>:
```
(lӓut-leaf2) configure
(leaf2:config)>  sadf sdfs
```

**Comment by Sripadvallabh** [comment]
Hi team, can anyone take a look into this issue. We are facing some deadlines for our app & some users want this functionality enabled.

**Comment by kmvanbrunt** [comment]
The `completer` argument is meant for tab completing one token.

> :param completer: tab completion function that provides choices for single argument

That's why `completerFn` isn't being called when you try completing anything after the first token.

If you wish to tab complete multiple tokens, you need to use the `parser` argument.

> :param parser: an argument parser which supports the tab completion of multiple arguments

Your code would look something like this:

```Python
input_parser = cmd2.Cmd2ArgumentParser(add_help=False)
input_parser.add_argument(
    'arg',
    nargs=argparse.ONE_OR_MORE,
    suppress_tab_hint=True,  # This is optional but recommended in this case. See note below.
    completer=completer,
)

userInput = self.read_input(
    Fore.CYAN + prompt + Style.RESET_ALL,
    history=history,
    completion_mode=cmd2.CompletionMode.CUSTOM,
    parser=input_parser
)
```

Notes:

1. `suppress_tab_hint` - Pressing tab normally displays the help text for the argument if no completion results match your input. Setting this attribute to `True` will suppress these hints. Defaults to `False`.  If you leave it set to `False`, then pass the `help` parameter in the `add_argument()` call.

2. `cmd2` tab completion supports completing strings with spaces. If anything in your completion dataset does contain spaces, `cmd2` will automatically quote your tab completion result.

**Comment by Sripadvallabh** [comment]
Thanks Kevin for your explanation.

Sorry for raising a issue without properly going through the doc. I had the mindset of an argparse completer & thought it would work here.
