### ISSUE TITLE
Is this the right module for me?

### ISSUE THREAD

**Issue by mgiaco** [python-cmd2/cmd2#135]
Hello,

For a project I  need  a Command interpreter which runs some commands one after on from a file. So it should be possible to load a speciall command file. And then the interpreter should interpret every command in that file.  I do not need any user interaction. I only need some automation so open the file and run it.

The file is:
```file 
ON 10 
CMD1
CMD10
RUN
SAVE
STOP M2
OFF
 ```
So every command should end in a callback and if the callback is finished the next line should be executed. 
I am wondering if I can use any standard module as a basis for the implementation. And cmd/cmd2 is one I have found therefore I ask here.

many thanks

**Comment by tleonhardt** [comment]
Hi @mgiaco,

cmd2 can easily do everything you need (plus a whole lot more).  The built-in **load** command runs commands one after another from a file.  It can be run directly from the interactive mode.  Alternatively, this can even be run directly from the command line.  Lets say your application which contains a class which inherits from cmd2.Cmd is in the file **project.py**, you can load and run a file (named "script.txt") of commands directly from the command line with:

```bash
python project.py "load script.txt"
```

By default, the interpreter will run every command in that file in sequence.  But if any command returns **True**, then that tells the interpreter that there was a problem and it exits early.

If you want a more complicated control flow, then the **pyscript** command enables running commands via a Python script and inspecting the results of previous commands as you go along, but that is a little more complicated.

I would recommend looking at and playing with some of the examples in the **examples** directory.

**Comment by mgiaco** [comment]
@tleonhardt  many thanks. Okay so it is also possible to add some timed control flow. So run the interpret in a separated thread and each command should be interpreted with a timeslice of 1 second should be possible with some custom code. 
 
thx

**Comment by tleonhardt** [comment]
@mgiaco Yes, it is possible to add timed control flow via Python scripting and the **pyscript** command.  Your commands can spawn off a background thread to do work and your Python scripts can do whatever processing you wish.  I do this sort of thing on a regular basis for the apps I design based on cmd2.  You need to write the custom code for where and how data from your asynchronous commands gets stored.

**Comment by mgiaco** [comment]
Okay many thanks. But what do you mean with pyscript => I only know pyscript as a module for postscript.
Can I found any code sample?

**Comment by tleonhardt** [comment]
**pyscript** is a command built into the cmd2 framework which allows you to run Python scripts within a cmd2 application.  These scripts can run custom cmd2 commands and be used to automate conditional control flow.

See the **python_scripting.py** example cmd2 application:
https://github.com/python-cmd2/cmd2/blob/master/examples/python_scripting.py

And look at the **conditional.py** example Python script for use with it via the **pyscript** command:
https://github.com/python-cmd2/cmd2/blob/master/examples/scripts/conditional.py

So you could run the python_scripting.py cmd2 application like so:

```Bash
cd examples
python3 python_scripting.py
```
Then within it you can run the conditional.py script like so:

```Bash
'.../cmd2/examples' $ pyscript scripts/conditional.py ~
```
where "~" is an argument passed to the script which is either a relative or absolute path to a directory.

**Comment by tleonhardt** [comment]
@mgiaco I'm going to close this issue since there isn't a bug or feature request associated with it.  If you have any more questions, please feel free to ask.  

Good luck!

**Comment by mgiaco** [comment]
@tleonhardt 
Hey Todd,

So now I need to implement that stuff what I asked. So first I try a little example.

```python

from cmd2 import Cmd


class Job(Cmd):
    def __init__(self, name=''):
        self.name = name
        self.state = 'not started'
        Cmd.__init__(self, use_ipython=False)

    def do_run(self, *args):
        self.state = 'started'
        print(self)

    def do_stop(self, *args):
        self.state = 'ended'
        print(self)

    def do_pause(self, *args):
        self.state = 'paused'
        print(self)

    def do_resume(self, *args):
        self.state = 'resumed'
        print(self)

    def do_raise_exc(self, *args):
        self.state = 'exc'
        print(self)
        raise RuntimeError('some error')
    
    def __str__(self):
        return 'job %(name)s %(state)s' % vars(self)

if __name__ == '__main__':
    job = Job()

    with open('test.cmd') as f:
        job.cmdqueue.extend(f.read().splitlines())

    job.cmdloop()
```

And the file test.cmd

```text
run
stop
pause
resume
raise_exc
stop
quit
```

So I feed the jobs to the cmdqueue and run the loop. Is there a better way to go? Is it possible to:

feed the queue
start/run the queue
and if the queue is empty ... do nothing i do not need to run the queue.
Or can i stop the cmdloop in a way feed the queue and start the cmdloop and also stop it after the last command is processed

Is there any example around how I can modify the timed behaviour what I asked for?

many thanks

**Comment by tleonhardt** [comment]
@mgiaco 
Hey Mathias,

If you want to run a script at time of application invocation, you can directly pass arguments such as a load command on the command line like so:
```bash
python job.py @test.cmd
```
Or equivalently:
```bash
python job.py "load test.cmd"
```

In either case you don't need to manually feed the cmdqueue so the bottom of your script can just be:
```python
if __name__ == '__main__':
    job = Job()
    job.cmdloop()
```

If you want to do something more complicated or exotic, you can manage your own event loop instead of running the cmd2.Cmd.cmdloop().  For an example of how to do this see the **event_loops.py** example in the *examples* directory.  In essence you can add whatever timed control flow you want and you call each individual command with ``onecmd_plus_hooks`` and you make sure to call ``preloop`` at the beginning and ``postloop`` at the end.

**Comment by mgiaco** [comment]
Okay that's also a nice feature which i will use. But the second use case is: The app runs I receive a file over a network stream. Once the transmitted file is completed I will start the automation of that file. 

Ah okay ... So that means I have to implement the timed flow by myself okay sounds good. With that it should also be possible to change the timing in the flow of the commands. Something like this:

Possible Commands:

START
TIME_PER_CMD 1sec # start with 1 second per command
CMD1
CMD2
CMD3
TIME_PER_CMD 3sec # now run the following commands with 3 second tick rate
CMD4
CMD5
...
END

Okay I will take a look at those examples and try to implement a example for that. Maybe this is also interesting for others.

Yes many thanks - i hope it is no problem if I will come back here for questions.
cheers

**Comment by tleonhardt** [comment]
If you come up with an example you are happy with, please feel free to submit a Pull Request and add it to the examples directory.

And yes, feel free to come back here for questions.

**Comment by mgiaco** [comment]
Hi, 

So are you sure I can run the command on startup? I have tried it but it does not work for me.

```python
from cmd2 import Cmd


class Job(Cmd):
    def __init__(self, name=''):
        self.name = name
        self.state = 'not started'
        self.allow_cli_args = False
        Cmd.__init__(self, use_ipython=False)

    def do_run(self, *args):
        self.state = 'started' + str(args)
        print(self)

    def do_stop(self, *args):
        self.state = 'ended' + str(args)
        print(self)

    def do_pause(self, *args):
        self.state = 'paused' + str(args)
        print(self)

    def do_resume(self, *args):
        self.state = 'resumed' + str(args)
        print(self)

    def do_cmd1(self, *args):
        self.state = 'cmd1' + str(args)
        print(self)

    def do_cmd2(self, *args):
        self.state = 'cmd2' + str(args)
        print(self)

    def do_raise_exc(self, *args):
        self.state = 'exc' + str(args)
        print(self)
        raise RuntimeError('some error')

    def __str__(self):
        return 'job %(name)s %(state)s' % vars(self)


if __name__ == '__main__':
    job = Job()
    job.cmdloop()
```

test.cmd

```
run
stop
resume
```

I run: 

```
python job.py @test.cmd

```


I only see the command line but no running commands.
What I am doing wrong here?

**Comment by tleonhardt** [comment]
What you have done wrong is to set ``self.allow_cli_args`` to ``False``.  This is telling it to not allow you to pass in commands at the command-line.

Set that variable to ``True`` (or just don't set it since it is ``True`` by default) and you will be able to pass in commands on the command-line.

**Comment by mgiaco** [comment]
Oh .. sorry :-)

**Comment by mgiaco** [comment]
@tleonhardt 

What is the best way to extend a running python Qt app with cmd2? I think adding a thread and run cmdloop() in that thread did not work. 

many thanks

**Comment by tleonhardt** [comment]
@mgiaco 
Since cmd2 is fundamentally a command-line (i.e. terminal) application, you need a way to have a terminal embedded within your PyQt GUI application.  How to do that is really a PyQt question.  I'm not super-familiar with PyQt, so I'm probably not the guy to answer it for you.  But maybe this StackOverflow post will be helpful:
https://stackoverflow.com/questions/29112349/how-to-use-a-terminal-embedded-in-a-pyqt-gui

**Comment by mgiaco** [comment]
Hi @tleonhardt 

So now I working on that problem. So concerning the scripting I mentioned at the beginning of this conversation.... You told me, that it should be possible to add a conditional and time controlled behavior with pyscript as shown in the python_scripting.py example. So tried that example  and it worked as expected. I also read the code and now I understand what you mean I think. 

So no I taught i will do it that way:  I add some class add my special command with my special CmdResult and so on... Then instead of loading a commands.txt use a commands.py for example and there I program my controlled and conditional scripting flow.  

1) Do you know a way how I can load a pyscript like i load a command.txt with @command.txt or "load command.txt"

2) If I want my commands in a file only. Do you think it is a good idea to load the commands.txt file in the commands.py script file  => then parse it and then feed the call each command with something like cmd( {}, {}).format(next_cmd, next_args) or so. 
Hm... or is there a better way for doing that. Do you know what I mean?

many thanks
mathias

**Comment by tleonhardt** [comment]
Hi @mgiaco 

The "commands at invocation" feature that allows you to run commands when you start the app by adding them on the command line works with all commands not just load or "@".  So you should be able to do something like "python3 yourapp.py 'pyscript your_script.py'".  You just need to put the command plus its arguments in quotes so the parser knows that is a single command.

I think it would be a better idea to run your commands within the Python script directly using syntax like **cmd('command_name command_args')** instead of loading the commands from commands.txt.  Look at the example Python script here for an example of what I'm talking about: https://github.com/python-cmd2/cmd2/blob/master/examples/scripts/conditional.py

I hope that answers your questions.

Good luck,

Todd

**Comment by mgiaco** [comment]
Hi,
Many thanks for your as always very quick response. Okay thanks i will try this later. Okay but the problem is the commands are not constant so the commands.txt changes by time.

**Comment by tleonhardt** [comment]
Are you saying that you have some other tool which is dynamically generating the **commands.txt** file?

**Comment by mgiaco** [comment]
Hi, no other tool. A user can generate some command.txt file and try to run it with the tool.

**Comment by tleonhardt** [comment]
Ok, I was just suggesting you have your Python script read the commands in the command.txt file and process them one at a time since you wanted some kind of special conditional or timing behavior that you can't get with the ``load`` command.

**Comment by mgiaco** [comment]
@tleonhardt 

Okay so now I think i do not need scripting but it is really nice. So I think I can handle everything inside each command also the time triggered behavior. And there is also some CmdResult I do not know before I have looked into the examples.

 ```python

import threading
import time
from random import randint

from cmd2 import Cmd, CmdResult

TIMEOUT_CMD2 = 5


class Job(Cmd):
    def __init__(self, name=''):
        self.name = name
        self.state = 'not started'
        self._connected = False
        Cmd.__init__(self, use_ipython=False)

    def _try_to_connect(self):
        sleep_time = randint(0, 5)
        print("wait for {} seconds".format(sleep_time))
        time.sleep(sleep_time)

        if 2 <= sleep_time <= 3:
            self._connected = True
            print("connected...")
        else:
            self._connected = False
            print("could not connect...")

        # save connected state in CmdResult
        self._last_result = CmdResult(self._connected)

    def do_connect(self, *args):
        self.state = 'try to connect to something ...' + str(args)
        t = threading.Thread(target=self._try_to_connect)
        t.start()
        t.join()
        if self._last_result:
            print("also do_connect says connected")
        else:
            print("also do_connect says could not connect")

    def do_disconnect(self, *args):
        if self._connected:
            self._connected = False
            self._last_result = None

    def do_cmd1(self, *args):
        if self._last_result is not None:
            print("last result was {}".format(self._last_result))
            self._last_result = None
        else:
            print("last result was None {}".format(self._last_result))

        if not self._connected:
            print("return because not connected")
            return

        self.state = 'command 1' + str(args)
        print(self)

    def do_cmd2(self, *args):

        if not self._connected:
            print("return because not connected")
            return

        self.state = 'command 2' + str(args)
        print(self)

    def do_cmd3(self, *args):

        if not self._connected:
            print("return because not connected")
            return

        print("... start ...")
        start_time = cur_time = time.time()
        self.state = 'command 3' + str(args)
        print(self)
        while cur_time <= start_time + TIMEOUT_CMD2:
            time.sleep(1)
            cur_time = time.time()
        print("... ende ...")

    def __str__(self):
        return 'job %(name)s %(state)s' % vars(self)


if __name__ == '__main__':
    job = Job()
    job.cmdloop()
```

So I think i can handle the timing in each command by using some class variables. So in the cmd3 command I measure the start and wait for some time. And i also can skip commands if I am not connect and so on. Do you think it is a bad style if I manage this in that way?

**Comment by kotfu** [comment]
I'm new to this thread, but perhaps I could offer two suggestions, one in this message, and I'll make another suggestion in the next reply.

I also have a project that uses **cmd2** and it has several commands which require a connection. I implemented it as a decorator. Instead of:

```python
   def do_cmd3(self, *args):

       if not self._connected:
           print("return because not connected")
           return

       print("... start ...")
       ...
```

I did something like this

```python
    @requires_connection
    def do_cmd3(self, *args):
        print("... start ...")
        ...
```

And then defined **@requires_connection** like this:

```python
def requires_connection(f):
    """decorator for interactive methods which require a connection"""
    def _requires_connection(self, *args, **kwargs):
        if self._connected:
            f(self, *args, **kwargs)
        else:
            # print the message
            self.perr('not connected')
    return _requires_connection

class Job(Cmd):
...
```

I found this decorator approach more convenient and easier to read. If you are interested in seeing the full source to this , it's available at https://github.com/tomcatmanager/tomcatmanager/blob/master/tomcatmanager/interactive_tomcat_manager.py

**Comment by kotfu** [comment]
My second suggestion relates to the timing. It may not exactly suit your needs, but **cmd2** has built in support to time each command and print how long it took.

```
(Cmd) help

Documented commands (type help <topic>):
========================================
_relative_load  help     mumble  pyscript  save  shell      speak
cmdenvironment  history  orate   quit      say   shortcuts
edit            load     py      run       set   show

(Cmd) set timing True
timing - was: False
now: True
Elapsed: 0:00:00.000169
(Cmd) help

Documented commands (type help <topic>):
========================================
_relative_load  help     mumble  pyscript  save  shell      speak
cmdenvironment  history  orate   quit      say   shortcuts
edit            load     py      run       set   show

Elapsed: 0:00:00.000397
```

You can set this from code by:

```python
class Job(Cmd):
   def __init__(self, name=''):
       self.timing = True
```

**Comment by tleonhardt** [comment]
@kotfu That is an excellent suggestion regarding the **requires_connection** decorator.

**Comment by mgiaco** [comment]
Cool many thanks. The decorator is really nice.

**Comment by tleonhardt** [comment]
@mgiaco ``CmdResult`` is a useful data structure which at this time is only used in examples and unit tests, but isn't used within built-in ``cmd2`` commands themselves (at least yet).  It serves as an example for one way which you can store the results of a command so they can be inspected within a Python script executed by the ``pyscript`` command or manually by an advanced user or developer during debugging via the ``ipy`` or ``py`` commands for running an embedded IPython or Python interpreter, respectively.

I didn't want to force one way of doing this on users, but I didn't want to show an example or two to give people an idea of what is possible.

**Comment by mgiaco** [comment]
Okay I understand, so I will add some result handling inside my derived class.

**Comment by mgiaco** [comment]
@tleonhardt 

Hi,

I came back to this thread, because I really do have some problems with extending the cmd queue.
I do have an app running cmd2 with the feature above - which works fine. 

But I also do have a RS232 connection to that app. My idea was use some simple protocol and extend the cmd queue with the commands coming from the RS232. The problem is that if I extend the queue from the RS232 rx thread nothing happens. Only when I hit enter on the shell the queue starts by running command after command.

What I am doing wrong here - I do not find the point why the loop dose not start if I extend the queue.

many thanks
cheers
mathias

**Comment by tleonhardt** [comment]
@mgiaco 
Hi,

In its default behavior a ``cmd2`` application using the built-in ``cmdloop`` method is a **line-oriented command interpreter**.  What this means is that the main thread will block waiting for the user to enter a command and press **<Enter>** (technically it is actually running code within the C readline library that supports tab-completion and such and not purely blocking).  Once the user presses **<Enter>**, then the command line is interpreted and the desired command is executed.  Once that command finishes executing, a new prompt is issued and the loop blocks again waiting for the user to enter a command and press **<Enter>**.

So even if you have a separate thread populating the ``cmdqueue``, no commands placed into that queue will execute until the main loop unblocks.

If you desire different behavior, then you should probably not use the built-in ``cmdloop`` and implement your own main loop which would in turn rely on either ``runcmds_plus_hooks`` or ``onecmd_plus_hooks`` for the actual command execution.

**Comment by mgiaco** [comment]
@tleonhardt 
Hi Todd,

Many thanks I taught that this was the problem. Okay but I do really like the cmdloop -> so I mean that feature that I can control the app over the command line. But I do net the second channel over the Serial Line. So I changed nothing except that I feed in the commands coming from the serial line with onecmd_plus_hook - no it works.  Is it okay that I use it that way or would you say that there could be some strange behavior someday. So that is not what you told but I really would like to have the shell also.

**Comment by tleonhardt** [comment]
@mgiaco 
Hi Mathias,

As long as you don't have any thread synchronization issues, what you are doing should work fine.  With the way you are doing it you may get two commands running at the same time, one from the serial line via ``onecmd_plus_hooks`` and one from the ``cmdloop``.  If there are any data structures in your application which need protection for multithreaded access, you may want to add something like an ``RLock``, but other than that I think what you are doing is fine.  

If one of the commands which could be run over the serial line is a ``load`` to kick off a script, then I would recommend using ``runcmds_plus_hooks`` instead of ``onecmd_plus_hooks`` because that method will appropriately deal with running commands which ``load`` places in the cmdqueue before returning.

**Comment by mgiaco** [comment]
@tleonhardt 
many many thanks for your as always very fast support.

**Comment by mgiaco** [comment]
Hi Todd,

I am back again :-)  
I do have a question concerning feeding in with ```onecmd_plus_hooks or``` ```runcmds_plus_hooks```.
I do have some performance problems when I feed in some new command - it takes some long time before the processing of the command begins. Do you know a way how I can accelerate that behaviour?

many thanks

**Comment by tleonhardt** [comment]
Hi Mathias,

I'm not aware of anything in particular within ``cmd2`` which would limit the performance of what you are trying to do, at least if you are dealing with typical human reaction-time type timescales.

Do you have any example code you can share that demonstrates these performance problems?

Whenever I encounter a performance problem, the first thing I do is profile the application to get actual hard data so I can understand what is slow.  You can use Python's build-in [cProfile](https://docs.python.org/3/library/profile.html) module to do this.

Once I find the actual problem, if it isn't something trivial to fix then I typically use [Cython](http://cython.org) to optimize the actual bottleneck.

If you are dealing with a very simple command/argument parsing situation and you don't mind giving up some ``cmd2`` features like command history, output redirection, piping command output to shell commands, hooks, command timing, etc., then you can bypass a bunch of ``cmd2`` logic and call the ``onecmd()`` method instead of the ``onecmd_plus_hooks()`` or ``runcmds_plus_hooks()`` methods.

The slowest part of cmd2 is the **pyparsing** routines which parse everything the user types in.  The parsing logic is quite complicated due to all of the features supported and possible edge cases.  It has never been a problem when dealing with humans typing commands in on a keyboard.  If you are trying to work at machine speeds, then this could present a bottleneck.  In a perfect world, I would like to replace the use of **pyparsing** in ``cmd2`` with something faster, but it would be a lot of work and I don't have the time for that anytime soon.

I hope some of that is helpful ;-)

Good luck!

-Todd

**Comment by mgiaco** [comment]
Hi Todd,

Many many thanks - I will try all that.

thanks
mathias
