### ISSUE TITLE
cmd2 0.7.3: cmd2.Cmd.completenames breaks existing users

### ISSUE THREAD

**Issue by amotoki** [python-cmd2/cmd2#137]
cmd2 0.7.3 now overrides completenames() method from cmd.Cmd and it requires consumers to pass 5 arguments. It is backward-incompatible change and breaks existing consumers.
One example affected is python-cliff. https://bugs.launchpad.net/python-cliff/+bug/1700250

**Comment by tleonhardt** [comment]
@amotoki Thank you for bringing this issue to my attention.

The new method signature matches what actually gets passed from readline and some of the new arguments are used to provide a welcome convenience to the end user.  It is unfortunate that the implementers of cmd chose to originally design this method in a fashion which isn't fully compatible with readline.

The ``completenames`` method should **never** be called by end users and should never have any direct consumers other than unit tests.

For python-cliff did this break actual usage or did it just break the unit tests?  In the past I have attempted to fix cliff unit tests related to changes I make in cmd2, but the OpenStack process is archaic.  I signed a million forms and in the end couldn't get the required tools to work for for me to make commits.

I am happy to work with you to modify the cliff unit tests so they work with the new version of cmd2.

If actual functionality of cliff beyond unit tests is broken, then I would be happy to work with you to discuss how we could modify cmd2 so that we can alleviate these issues.

**Comment by tleonhardt** [comment]
@amotoki I'm not that familiar with cliff, but another thing to potentially watch out for in the 0.7.3 release of cmd2 is the one change which was intentionally backwards incompatible.  See the "warning" in the release notes for more info:
https://github.com/python-cmd2/cmd2/releases/tag/0.7.3

In summary, for all commands defined which use the **@options** decorator for OptParse argument parsing, by default the arguments are supplied to the commands now as a list of strings instead of a single string.  This dramatically simplifies the parsing logic an end user needs to write.

If you wish to restore the old way things worked, you just need to add this to the __init__ code of your class which derives from cmd2.Cmd:

```Python
cmd2.set_use_arg_list(False)
```

**Comment by tleonhardt** [comment]
@amotoki From what I can see from the cliff bug report, this isn't an issue with cmd2 and some minor changes to cliff unit tests will fix the problem. 

So I'm going to close this issue.  If my understanding is wrong, please let me know and I can re-open it.
