### ISSUE TITLE
Python 3.5 renames subprocess.mswindows

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#18]
Originally reported by: **Barry Warsaw (Bitbucket: [warsaw](http://bitbucket.org/warsaw), GitHub: [warsaw](http://github.com/warsaw))**

----------------------------------------

Actually, subprocess.mswindows is an internal-only API so ideally it shouldn't be used at all.  However, in Python 3.5 the attribute has been renamed to subprocess._mswindows, thus breaking cmd2.

You can just use `(sys.platform == 'win32')` which is the definition of subprocess.mswindows anyway.

----------------------------------------
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/18

**Comment by hozn** [comment]
I submitted a merge req (matching above suggestion) in #21

**Comment by FedericoCeratto** [comment]
Merged, thank you!

**Comment by PAStheLoD** [comment]
Hello,

First, sorry for bothering you on a closed issue! And second, could you (or anyone with access) release current master on PyPI? (So python-openstackclient - which uses cliff, which uses cmd2 - and probably a bunch of apps would not annoy users with that exception.)

Or is there some reason the recent changes haven't been released (no upload since 2014)?

**Comment by FedericoCeratto** [comment]
@PAStheLoD v. 0.6.9 has been released. The original author stopped maintaining the library.  Co-maintainers are very welcome :)
