### ISSUE TITLE
Cmd2 . decorator @options([make_option( .....

### ISSUE THREAD

**Issue by FedericoCeratto** [python-cmd2/cmd2#20]
Originally reported by: **Anonymous**

---

as options may be added at end of line (optparse) ex : speak -p aaaaa bbbbb  -r2 ( instead of speak -p -r2.....,  it happens in def :  remaining_args(..) that the `\s_$ entails an attribute error because no matching
pattern = '\s+'.join(re.escape(a) for a in newArgList) + '\s_$'
Bypassed by removing '\s*$ in above.
regards

---
- Bitbucket: https://bitbucket.org/catherinedevlin/cmd2/issue/20

**Comment by hatRiot** [comment]
If this is even supported anymore, optparse is deprecated and argparse should be used instead.

**Comment by tleonhardt** [comment]
I put in a try/except to deal with this case of an AttributeError appropriately.  It is fixed in the latest code and a couple unit tests have been added related to it.

@hatRiot I agree that we should look into replacing optparse with argparse since optparse is deprecated.  I'll create a new issue specifically for that.
