### ISSUE TITLE
Piping input from the shell behaves poorly

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#218]
```$ echo help | python examples/example.py
(Cmd)
Documented commands (type help <topic>):
========================================
_relative_load  help     mumble  pyscript  save  shell      speak
cmdenvironment  history  orate   quit      say   shortcuts
edit            load     py      run       set   show

stty: stdin isn't a terminal
(Cmd) stty: stdin isn't a terminal
```

Notice how the command is not output by **Cmd2**, but the prompt is. This means that the output can not be used as a transcript. There are several options to improve the behavior:

1. Output the prompt and the command. This makes the output a testable transcript.
2. Output neither the prompt or the command. This makes the output easily parseable by other command line utilities that may want to consume only the output. This is the current behavior of the **load** command, which does a similar thing.
3. Make some setting which allows you to choose between option 1 or option 2. Subclasses of **Cmd2** could get this setting from a command line switch, or permanently set it one way or the other.

The other problem are the mysterious 'stty: stdin isn't a terminal' messages. A cursory glance at the code in **_cmdloop** seems to indicate that **Cmd2** always expects to read input from a tty. When we run the **load** command, the commands to run get added to **.cmdqueue** and nothing is read from stdin.

**Comment by tleonhardt** [comment]
As far as the options go, I like either **2** or **3**.

The **echo** setting may be the appropriate setting.  If it is on, then the command name (but not prompt) will print out when using the ``load`` command for example.  Now that I think about it, it would be better if the prompt printed as well.

Regarding the *stty: stdin isn't a terminal* messages, that only happens if you are using input direction at invocation of your cmd2 app.

Supposing the "help.txt" file contains just the text "help", if you do the following from the command-line:

```Bash
./cmd2.py < help.txt
```
Then you will see the output with the mysterious messages.

However, if you do the following within a running ``cmd2`` app's cmdlloop(), the stty messages will not appear:

```Bash
(Cmd) < help.txt

Documented commands (type help <topic>):
========================================
_relative_load  edit  history  py        quit  save  shell      show
cmdenvironment  help  load     pyscript  run   set   shortcuts

```

**Comment by tleonhardt** [comment]
Of possible relevance ... ``cmd2`` and its ``cmd`` parent allow you to pass a **stdin** argument to the initializer.  If this argument isn't ``None``, then ``cmd`` uses it to set ``self.stdin``, otherwise ``self.stdin`` gets set to ``sys.stdin``.

**Comment by tleonhardt** [comment]
I committed a small change earlier which fixed the issue with the ``load`` command not printing the prompt when **echo** is set to True.

**Comment by kotfu** [comment]
I've created a new branch to start working on this.
