### ISSUE TITLE
OutputTrap and Shell Command Traceback

### ISSUE THREAD

**Issue by soggysec** [python-cmd2/cmd2#229]
Hi Guys,

I'm having an issue, and I'm not sure if it's something I'm doing wrong, or a bug with cmd2. 

I have an OutputTrap defined: 

        class OutputTrap(object):
             def __init__(self, handle):
                 self.handle = handle

             def write(self, msg):
                 self.handle.cli.userLog(msg.rstrip())
 
             def flush(self):
                 pass
 
             def read(self):
                 return 'stdin trap!'
 
         self.stdout = OutputTrap(self)

The userLog() looks like:

def userLog(msg):
    print "[+] {}".format(msg)

When I try to run a shell command: !ls, I get:

> !ls
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 774, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 924, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 1225, in do_shell
    proc = subprocess.Popen(command, stdout=self.stdout, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 703, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 1137, in _get_handles
    c2pwrite = stdout.fileno()
AttributeError: 'OutputTrap' object has no attribute 'fileno'
EXCEPTION of type 'AttributeError' occurred with message: ''OutputTrap' object has no attribute 'fileno''
To enable full traceback, run the following command:  'set debug true'

So the issue is obviously that I don't have "fileno" function defined in my OutputTrap, but I'm not sure what the best way to handle that is. If I hard-code self.fileno = sys.stdout.fileno, everything works fine, but that's obviously not truly solving the problem, because if I change userLog to do something other than print, the logic will be wrong. 

Please advise?

Thanks!

**Comment by tleonhardt** [comment]
@soggysec I tested this issue using the following minimal cmd2 application:

```Python
#!/usr/bin/env python
import cmd2

class OutputTrap(object):
    def __init__(self, handle):
        self.stdout = handle.stdout

    def write(self, msg):
        self.stdout.write(msg.rstrip() + '\n')

    def flush(self):
        pass

    def read(self):
        return 'stdin trap!'

class TestApp(cmd2.Cmd):
    def __init__(self):
        cmd2.Cmd.__init__(self)

if __name__ == '__main__':
    app = TestApp()
    app.stdout = OutputTrap(app)
    app.cmdloop()
```

I verified that this issue is present on both Python 2.7 and 3.x.  

However, I don't see a clear way to alleviate the underlying issue which would make sense in general for all use cases.  The underlying problem is that Python's subprocess module expects a legitimate file object (or at least file-like) if you pass it a stdout in the subprocess.Popen() call.  Your OutputTrap class isn't a legitimate file-like object.

Possible solutions I can see include:

1.  Replace **stdout=self.stdout** with **stdout=sys.stdout**
    - Advantage:  Simple
    - Disadvantage:  Output always goes to screen and is never redirected
2.  Replace **stdout=self.stdout** with **stdout=subprocess.PIPE**
    - Advantage:  Simple (just need to remember to get the output from calling communicate)
    - Disadvantage:  Many shell commands behave completely differently when their stdout is a pipe versus a tty
3.  Make your ``OutputTrap`` class more file-like so subprocess.Popen() will behave correctly
    - Advantage:  Don't have to change cmd2
    - Disadvantage:  Potentially more work on your part
4.  Override the ``do_shell`` method in your application to behave like you would like it to
    - Advantage:  Don't have to change cmd2 and easier than option 3 above
    - Disadvantage: Not a general solution

So what are you thoughts?  I'm leaning towards not trying to "fix" cmd2 for this issue because it does appear to be behaving as intended and I can't think of a way to work around this which would make sense in general for all use cases.  Without knowing more about what you want to do, I think that Option 4 above probably seems like the best path forward for you.  You can effectively choose to implement either Option 1 or Option 2 above for your particular case by overriding the ``do_shell`` method in your application.

**Comment by soggysec** [comment]
I think your do_shell override is elegant enough. I kind of liked Option 3, and but haven't figured out a clever way to make it work. I wanted to write a kind of loopback that basically created its own file handle-like object, and piped everything to the overloaded write function. I think for now, I'll go with your suggested easy solution. Thanks!
