### ISSUE TITLE
emptyline() from cmd cannot be used

### ISSUE THREAD

**Issue by hukka** [python-cmd2/cmd2#24]
Using cmd2 as drop in replacement breaks using https://docs.python.org/3/library/cmd.html#cmd.Cmd.emptyline, as cmd2 completely ignores empty lines (onecmd_plus_hooks catches EmptyStatements and just returns 0). Either this is a bug or needs a note in the docs.

**Comment by tleonhardt** [comment]
@hukka Thanks for pointing this out.  A note has been added to Overview section of the cmd2 documentation:  https://cmd2.readthedocs.io/en/latest/overview.html

**Comment by morzen** [comment]
Hello apologies for re-writting here but i wanted to know if this would ever be fixed or you had alternatives to the emptyline() function cause i am in need of updating something everytime a command is entered or not so empty line or not the prompt need to update.

thanks

**Comment by morzen** [comment]
PS: because the issue is that no lice cycle hook or post or pre command hook can work or at least if an empty line isn't considered as a command.

IE: if I enter a command like (prompt which need to update at every iteration): ls

in this case, the prompt will update thx to pre or post command hooks

but should I enter nothing 
 (prompt which needs to update at every iteration):

the prompt won't update

**Comment by kmvanbrunt** [comment]
@morzen You will want to write a Command Finalization Hook. This type of hook runs after every command and empty line.
https://cmd2.readthedocs.io/en/stable/features/hooks.html#command-finalization-hooks

Here's a simple example

```Python
from cmd2 import (
    cmd2,
)


class MyApp(cmd2.Cmd):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.register_cmdfinalization_hook(self.prompt_updater_hook)

    def prompt_updater_hook(self, data: cmd2.plugin.CommandFinalizationData) -> cmd2.plugin.CommandFinalizationData:
        """
        This runs after each command and empty lines
        """
        # This check is optional. Since no prompt is displayed during a script, you can wait until it finishes
        # before updating the prompt instead of updating the prompt after every command in the script.
        if not (self.in_script() or self.in_pyscript()):
            # Update the prompt
            self.prompt = "new prompt> "
        return data


if __name__ == '__main__':
    app = MyApp()
    app.cmdloop()

```

**Comment by morzen** [comment]
oh man, you are my savior thanks =))

**Comment by kmvanbrunt** [comment]
@morzen You're welcome. Let us know if you have any other questions.

**Comment by morzen** [comment]
Well actually, yes i thought the backward compatibility with cmd would prevent some issue but one arose to the occasion.

in a  former version of my program which was using cmd i was able to use back space and delete my commands if i had made a typo or anything without any issues.

But since moving on to cmd2  the back space key output ^H which is quite problematic.

many thanks ^^
