### ISSUE TITLE
Use @with_argument_parser for all methods which require argument parsing

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#250]
Many methods in cmd2 utilize the now deprecated **@options** decorator, ex. **do_pyscript()** and **do_history()**. Other methods like **do_save()** use `pyparsing`, which works, but it too should probably be migrated to **@with_argument_parser**. **do_set()** does custom argument parsing not utilizing any library. Still other methods do no argument parsing, but probably should, like **do_load()**. All of these should be moved to `argparse` based argument processing.

Methods which implement single word commands, like **do_quit()** and **do_shortcuts()** could be left to ignore all passed arguments, which is what they do now.

**Comment by tleonhardt** [comment]
Oh wow, I didn't realize that **do_save()** was using ``pyparsing`` for its parsing logic. 

Everything should be migrated to use the argparse-based decorator for parsing if it needs special parsing or perhaps just the decorator which causes a list of arguments to get passed if it doesn't need special parsing but needs more than a single argument.  Some of the existing functions which use **@options**, such as **do_pyscript()** were using it with an empty option list just so they could get a list of argument strings intstead of a single string - i.e. to take advantage of the shlex parsing provided by the **@options** decorator.

The custom argument parsing in **do_set()** is pretty non-standard in terms of the way it tries hard to cast anything into the type expected for the given setting, so I wouldn't recommend attempting to port that to an argparse-based solution.

**Comment by kotfu** [comment]
## no changes required
- [x] **do_eos()** - can't pass arguments to this command
- [x] **do_eof()** - can't pass arguments to this command
- [x] **do_quit()** - ignores all arguments passed

## accepts only a single argument
modified all these to use the **@with_argument_list** decorator
- [x] **do__relative_load()**
- [x] **do_load()**
- [x] **do_help()**

## still to investigate
- [ ] **do_cmdenvironment()**
- [ ] **do_edit()**
- [ ] **do_history()**
- [ ] **do_py()**
- [ ] **do_pyscript()**
- [ ] **do_run()**
- [ ] **do_save()**
- [ ] **do_set()**
- [ ] **do_shell()**
- [ ] **do_shortcuts()**
- [ ] **do_show'()**

**Comment by tleonhardt** [comment]
I have some thoughts/comments regarding a few of the "to investigate" methods.  They aren't necessarily related to this issue, but they could potentially be, so I thought I would share them ...

I've been thinking of eliminating the **do_cmdenvironment()** method.  I don't think that it is something which is generically useful to end users of ``cmd2`` applications and as such it feels out of place.  It is mildly useful for developers while developing.

I've also been considering eliminating the **do_show()** method and turning it into a non-command method since it is called by **do_set()** anyways when **do_set()** is invoked with no arguments.  Having both **set** and **show** feel redundant.

I've also toyed with the idea of either eliminating or modifying the **do_shortcuts()** method in the long run.  The main problem with this one is I've seen multiple end users get confused that they can't create new shortcuts with this command.  So it might make sense to eliminate it and find a clever way of displaying shortcuts in the built-in help.  Alternatively, it might make sense to find a way to modify it to allow users to add new shortcuts.

Do you have an opinion on any of this one way or the other?

**Comment by kotfu** [comment]
Never used **do_cmdenvironment()** so no opinion there. I agree **do_show()** feels redundant.

As for **do_shortcuts()**, my initial reaction is that I don't want a way for users to create/modify shortcuts at runtime. But I really like the idea of eliminating the **shortcuts** command and instead modify help so that it shows what the shortcut is a synonym for.

**Comment by kotfu** [comment]
Just looked at **do_cmdenvironment()**, and agree its not generally useful to end users. However, since it is potentially useful to developers, what if we modified the **set** command to accept a **-a/--all** option. If you do "set --all" then you get the standard settings, and then a blank line, and then a line that says "Read only settings", and then the output of **cmdenvironment**. Then it would still be available, but would be less confusing for end users because there would be no **cmdenvironment** command in help.

**Comment by tleonhardt** [comment]
I think your above suggestion related to **do_cmdenvironment()** is an excellent one.  Eliminating the **cmdenvironment** command, but adding a flag to the **set** command which would then also display read-only settings (which is basically what cmdenvironment does) would give a simpler **help** menu for end users, but preserve access to the additional information developers may desire.
