### ISSUE TITLE
Consolidate functionality of editing, saving, and showing the history of commands entered

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#252]
The **do_history()** command allows you to search and slice history before displaying it. The **do_save()** command doesn't, but it will save history to a file. The **do_edit()** command lets you edit one history item and then run it. We should consolidate all the history functionality into a single command.

- [x] Add a **-o/--output-file** argument to **do_history()** which writes the selected history item(s) to the given file
- [x] Remove the **do_save()** method and it's associated tests
- [x] Add a **-r/--run** argument to **do_history()** to run the selected command(s)
- [x] Remove the **do_run()** method and it's associated tests
- [x] Add a **-e/--edit** argument to **do_history()** to let you edit the selected history item(s) in an editor. Run the contents of the edited file when the editor exits.
- [x] Modify **do_edit()** to not edit commands from history, just to edit files
- [x] Remove **_last_matching()** method
- [x] Remove **autorun_on_edit** attribute and setting

**Comment by tleonhardt** [comment]
Yeah, I like this idea a lot.  That puts the functionality in a more logical place.

**Comment by tleonhardt** [comment]
There are a couple more potentially desirable changes of a similar nature.  

First, the **run** command simply re-runs a command from the history.  We can probably added a **--run** argument to the **history** command which encompasses the same functionality.

Secondly, the **edit** command is a bit odd in its behavior where if it is passed an integer it edits that command number from the history (and runs the edited version when it exits), whereas if it is passed something that isn't an integer it edits that file.  It would probably make more logical sense to add a **--edit** argument to the **history** command that encompasses the functionality of editing and running a previous command and then have the **edit** command simply edit files.

I think these would be good changes to make.  They could be worked under this issue since they are all similar in nature, or we could create separate issues for them.

**Comment by kotfu** [comment]
I like all of this. **edit** does seem overloaded. I also discovered that you can already use the history command to save output to a file by using shell redirection, like:

    history -s > /tmp/history.txt

I've revised the issue description and my first comment to reflect all the changes discussed so far.
