### ISSUE TITLE
My transcript does not contain the output of commands

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#275]
I had written some tests manually that are now obsolete because of internal changes. I thought of using transcript based testing instead so this is my first try but I am not sure to do it correctly:
http://cmd2.readthedocs.io/en/latest/transcript.html
After running a few commands, I did `history 1:4 -t transcript.txt` which saves the following transcript.txt:
```
iperf-mptcp-0-0.pcap> load_pcap examples\/iperf-mptcp-0-0.pcap
iperf-mptcp-0-0.pcap> lc
iperf-mptcp-0-0.pcap> ls 0
iperf-mptcp-0-0.pcap> ls 1
```
This lacks the output, here is the complete session:

```
+Ready>load_pcap examples/iperf-mptcp-0-0.pcap
>>> examples/iperf-mptcp-0-0.pcap
/home/teto/mptcpanalyzer/mptcpanalyzer/data.py:144: ParserWarning: Both a converter and dtype were specified for column tcp.flags - only the converter will be used
  "mptcp.duplicated_dsn": lambda x: list(map(int, x.split(','))) if x is not None else np.nan,
+iperf-mptcp-0-0.pcap> lc
>>> 
1 mptcp connection(s)
Description of mptcp.stream 0 
The connection has 4 subflow(s) (client/server): 
	tcp.stream 0.0 : 10.1.0.1:5001.0  <-> 10.2.0.1:5001.0 
	tcp.stream 1.0 : 10.1.1.1:43376.0  <-> 10.2.0.1:5001.0 
	tcp.stream 2.0 : 10.1.0.1:49078.0  <-> 10.2.1.1:5001.0 
	tcp.stream 3.0 : 10.1.1.1:57841.0  <-> 10.2.1.1:5001.0 
+iperf-mptcp-0-0.pcap> ls 0
>>> 0
Description of mptcp.stream 0 
The connection has 4 subflow(s) (client/server): 
	tcp.stream 0.0 : 10.1.0.1:5001.0  <-> 10.2.0.1:5001.0 
	tcp.stream 1.0 : 10.1.1.1:43376.0  <-> 10.2.0.1:5001.0 
	tcp.stream 2.0 : 10.1.0.1:49078.0  <-> 10.2.1.1:5001.0 
	tcp.stream 3.0 : 10.1.1.1:57841.0  <-> 10.2.1.1:5001.0 
+iperf-mptcp-0-0.pcap> ls 1
>>> 1
Traceback (most recent call last):
  File "/nix/store/75apj1nkg5i2sy4hhfw8bjgx2dh2ghz9-python3.6-cmd2-0.8.0/lib/python3.6/site-packages/cmd2.py", line 981, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/nix/store/75apj1nkg5i2sy4hhfw8bjgx2dh2ghz9-python3.6-cmd2-0.8.0/lib/python3.6/site-packages/cmd2.py", line 1179, in onecmd
    stop = func(statement)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 65, in wrapped
    return f(self, *args)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 296, in do_list_subflows
    self.list_subflows(args.mptcpstream)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 65, in wrapped
    return f(self, *args)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 300, in list_subflows
    con = MpTcpConnection.build_from_dataframe(self.data, mptcpstreamid)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/connection.py", line 215, in build_from_dataframe
    raise MpTcpException("No packet with this mptcp.stream id %r" % mptcpstreamid)
mptcpanalyzer.MpTcpException: No packet with this mptcp.stream id 1
EXCEPTION of type 'MpTcpException' occurred with message: 'No packet with this mptcp.stream id 1'
To enable full traceback, run the following command:  'set debug true'
+iperf-mptcp-0-0.pcap> history
>>> 
-------------------------[1]
load_pcap examples/iperf-mptcp-0-0.pcap
-------------------------[2]
lc
-------------------------[3]
ls 0
-------------------------[4]
ls 1
+iperf-mptcp-0-0.pcap> history 1:4 -t transcript.txt
>>> 1:4 -t transcript.txt
>>> examples/iperf-mptcp-0-0.pcap
/home/teto/mptcpanalyzer/mptcpanalyzer/data.py:144: ParserWarning: Both a converter and dtype were specified for column tcp.flags - only the converter will be used
  "mptcp.duplicated_dsn": lambda x: list(map(int, x.split(','))) if x is not None else np.nan,
>>> 
1 mptcp connection(s)
Description of mptcp.stream 0 
The connection has 4 subflow(s) (client/server): 
	tcp.stream 0.0 : 10.1.0.1:5001.0  <-> 10.2.0.1:5001.0 
	tcp.stream 1.0 : 10.1.1.1:43376.0  <-> 10.2.0.1:5001.0 
	tcp.stream 2.0 : 10.1.0.1:49078.0  <-> 10.2.1.1:5001.0 
	tcp.stream 3.0 : 10.1.1.1:57841.0  <-> 10.2.1.1:5001.0 
>>> 0
Description of mptcp.stream 0 
The connection has 4 subflow(s) (client/server): 
	tcp.stream 0.0 : 10.1.0.1:5001.0  <-> 10.2.0.1:5001.0 
	tcp.stream 1.0 : 10.1.1.1:43376.0  <-> 10.2.0.1:5001.0 
	tcp.stream 2.0 : 10.1.0.1:49078.0  <-> 10.2.1.1:5001.0 
	tcp.stream 3.0 : 10.1.1.1:57841.0  <-> 10.2.1.1:5001.0 
>>> 1
Traceback (most recent call last):
  File "/nix/store/75apj1nkg5i2sy4hhfw8bjgx2dh2ghz9-python3.6-cmd2-0.8.0/lib/python3.6/site-packages/cmd2.py", line 981, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/nix/store/75apj1nkg5i2sy4hhfw8bjgx2dh2ghz9-python3.6-cmd2-0.8.0/lib/python3.6/site-packages/cmd2.py", line 1179, in onecmd
    stop = func(statement)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 65, in wrapped
    return f(self, *args)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 296, in do_list_subflows
    self.list_subflows(args.mptcpstream)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 65, in wrapped
    return f(self, *args)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 300, in list_subflows
    con = MpTcpConnection.build_from_dataframe(self.data, mptcpstreamid)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/connection.py", line 215, in build_from_dataframe
    raise MpTcpException("No packet with this mptcp.stream id %r" % mptcpstreamid)
mptcpanalyzer.MpTcpException: No packet with this mptcp.stream id 1
EXCEPTION of type 'MpTcpException' occurred with message: 'No packet with this mptcp.stream id 1'
To enable full traceback, run the following command:  'set debug true'
4 commands and outputs saved to transcript file 'transcript.txt'
```
EDIT: could that be because I use a custom prompt ?

**Comment by tleonhardt** [comment]
@teto 
In your ``cmd2`` application, how are you sending your output to the screen?  

In general ``cmd2`` makes some important assumptions regarding how you generate output for users.  I'm thinking we may want to make it a little more clear in the documentation what these assumptions are.   The main assumption is that all output for the user is generated using one of the following three methods:
- ``self.poutout()`` - all normal output
    - This always gets sent to ``self.stdout`` which always gets redirected when appropriate
- ``self.perror()`` - all exceptional output (errors)
    - This always gets sent to ``sys.stderr`` which almost never gets redirected
- ``self.pfeedback()`` - for printing non-essential feedback (can be silenced)
    - Sometimes gets sent to ``self.stdout`` and other times to ``sys.stderr``

The ability to generate transcript tests from the history using **history -t** makes the above assumptions and it further assumes that only output written to ``self.stdout`` (via ``self.poutput()`` gets written to the transcript file.

As long as you are setting your custom prompt using ``self.prompt``, then it should be fine; transcript tests work with custom prompts.  Transcript testing goes a little beyond that even, it purposely strips off any ANSI escape codes from your custom prompt to so that it only compares text and doesn't compare color.

**Comment by teto** [comment]
I had no idea, poutput doesn't appear in http://cmd2.readthedocs.io/en/latest/transcript.html.
Couldn't the function hijack the stdout temporarily though ? use its own fd and write it on the regular standout  as well as in the transcript ?
I had not realized the project was so lively (seen 0.8 this morning). Thanks for your work and the new features !

**Comment by tleonhardt** [comment]
That function is already hijacking ``self.stdout`` and redirecting it to a file.  I'd have to look at it - we might be able to hijack ``sys.stdout`` and also redirect it to that file.  But in order to get all of the features of ``cmd2`` to work properly, such as redirecting command output to a file and the ability to pipe command output to a shell command, it is important to use ``self.poutput()`` or ``self.stdout.write()``.  If your end users are POSIX-shell savvy, then those are really killer features.  I can't tell you how many times the ability to pipe command output to **grep** has just rocked socks.

At the very least I will keep this issue open and try to improve the documentation to let users know they should be using ``poutput()``.

@kotfu and I have been busy lately!  ;-)  We managed to get a bunch of good features into the 0.8 release.  I've gotten a lot of positive feedback about the new argparse decorators and I love how they open up the ability to support sub-commands.  We also have some really cool stuff coming up in the 0.8.1 release - in particular the ability to have sub-menus and persistent readline history.  Your thanks is appreciated and we are glad you like it.
