### ISSUE TITLE
Consider adding synonym capabilities

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#277]
It would be nice if you could teach cmd2 about synonyms for commands.

Say for example I create a command called **config** which shows the contents of a configuration file. I would like to make that same functionality available in a command called **settings**. I can make that happen by creating a **do_settings()** method which calls **do_config()**, but I have to remember to handle the help messages. This gets more complicated if you are using either of the argparser decorators because you may have to create two parsers, identical except for the **prog** parameter. The other sub-optimal thing is how the **help** command behaves. It shows both commands, but there is no indication that they are synonyms.

It would be great if you could do something like:
```
cmd2.synonyms = { 'config': ['settings', 'my_other_synonym']}
```
and have cmd2 do all the work: make the synonym command names work, with necessary changes to argparser **prog** parameters, and then display the help in such a way that it's easy to see which commands are synonyms for what.

**Comment by tleonhardt** [comment]
The current ability to add shortcuts basically functions as an alias capability, but there is now ability to get help on the shortcut.

There is also the ability to easily set another do_* method equal to an existing one to create and alias, but this also has issues.

It would be nice if there were something like a ``@alias(do_foo)`` decorator that could be applied to a **do_*** method and automatically creates an alias/synonym which properly deals with the issues you mention above.

**Comment by tleonhardt** [comment]
I think it would be cool if there was some sort of **alias** command that an end-user could use at run-time to create aliases in a fashion similar to how ``Bash`` aliases are created.

It would also be nice if there was an option for reading these aliases from some sort of configuration file at application startup time.  That could allow specific end users to customize an application for their needs without changing code.

**Comment by tleonhardt** [comment]
@kmvanbrunt Do you have any ideas for a good way to architect this sort of alias/synonym feature?  I'm curious since both @kotfu and I like the idea and it seems like something which would be fairly generically useful.  Moreover, we would want both **help** and tab-completion to work properly for command aliases and I know you have better insight into the overall tab-completion architecture than either of us.

**Comment by kmvanbrunt** [comment]
I don't think the **help** command should apply to aliases, since an alias isn't necessarily just a command. It could be an entire command line like the common `alias ll='ls -l'`. If you were to run a **man** command on ll, bash does not expand it first.  So basically aliases, like shortcuts, must be the first token on the command line for them to be expanded.

I currently tab complete shortcuts that aren't symbols and could easily do the same for aliases. In fact, I might just eliminate this behavior if aliases are implemented. We could just instruct users that shortcuts are meant to be symbols.

**Comment by tleonhardt** [comment]
I like the behavior that the **alias** command would just list all aliases if no arguments are given.

**Comment by tleonhardt** [comment]
@kotfu Does the recently added **alias** command meet the needs of what you envisioned with the synonym capability?  If not, we can re-open this Issue and/or create a new one.

**Comment by kotfu** [comment]
The recently implemented **alias** capability is better than what I had envisioned for synonyms, because the user can control it. No need to re-open this issue.
