### ISSUE TITLE
Consider removing support for case-insensitive commands

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#290]
Supporting case-insensitive command names via the ``cmd2.Cmd.case_insensitive`` attribute gets a little complicated.  How should the case-insensitiveness behave for shortucts?  What about sub-command names?

Does anyone actually use and and like support for case-insensitive commands?  If not, I would prefer to remove this "feature".  But if people do use it and like it then we won't touch it.

**Comment by tleonhardt** [comment]
@kotfu Do you have an opinion on this one way or the other?

**Comment by kotfu** [comment]
I can speak for an army of one (that's me 😄 ), but I think case insensitivity is a relic of poor system design from the 1970's that I would love to see disappear. I'm sure at some point in the distant past, it was easier to be case insensitive than to be case sensitive, but since the advent of "modern" stuff like ASCII, case insensitivity has just been a pain. I wouldn't feel a bit bad if we got rid of all case insensitivity support.

/rant
