### ISSUE TITLE
Add option to specify a startup script in the cmd2.Cmd.__init__()

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#317]
One thing which would make the new **alias** command dramatically more useful would be the ability to specify a script to automatically **load** at startup.

This script could run any arbitrary set of commands contained within the given ``cmd2`` application.  But one thing it would be particularly suitable for is allowing different end users to personalize their environment with custom aliases.

**Comment by MarkLalor** [comment]
I think this is super useful for much more than aliases! This was basically one of the first things I implemented in my own cmd2 app since it requires initialization to be useful. It's nice to be able to quickly add and remove things like "set debug true" as well.

I think it would be a good idea to encourage using an rc file for configuration in the documentation because as far as I can tell, it's the best (and probably easiest) way unless you have some complex initialization data. Especially in conjunction with settable parameters.
