### ISSUE TITLE
No module named cmd2

### ISSUE THREAD

**Issue by elohim971** [python-cmd2/cmd2#339]
Hello,
I would like to run a program.py with python but I get this error "No module named cmd2" even though I imported cmd2 and installed it... What could be wrong? What am I missing?

I've got Python 2.7.14 on Kali Linux via VirtualBox.

Thanks for your time

Jé

**Comment by tleonhardt** [comment]
Hi @elohim971,

Can you give us a little more information regarding how you installed ``cmd2`` on Kali and how you are launching your **program.py**?

The fact that you are using VirtualBox as your VM environment shouldn't matter.  Kali is Debian-based nowadays isn't it?  That should be fine - we regularly test on Debian.

**Comment by tleonhardt** [comment]
I just setup a VM with the latest version of Kali and installed ``cmd2`` using **pip** and was able to run one of the examples (after cloning this GitHub repo) just fine.

**Comment by elohim971** [comment]
Thank you for your quick answer already.

I imported cmd2 then **pip install** then **sudo apt-get install cmd2** just like that... maybe I missed a step, right?

"Kali is Debian-based nowadays isn't it?" How can I verify that on my computer? I don't really know :/

Thank you @tleonhardt

**Comment by tleonhardt** [comment]
I would recommend using **pip** to install ``cmd2`` instead of using **apt-get** because you will get a newer version of ``cmd2`` that way, though either one should work fine.

I did the following on my Kali VM:
```Bash
apt-get update
apt-get upgrade
apt-get dist-upgrade
pip install -U cmd2
mkdir src
cd src
git clone https://github.com/python-cmd2/cmd2
cd cmd2
./cmd2.py
```
This updated all files on the Kali distro, installed ``cmd2`` using **pip**, cloned the ``cmd2`` git repo, and then ran a completely bare-bones vanilla ``cmd2`` application.  This all worked fine. 

P.S.  Kali *is* Debian-based.  If **apt-get** exists, you can pretty much safely assume it is a Debian-based Linux distribution.

**Comment by elohim971** [comment]
Thank you, I did all of that but I got a problem after #apt-get upgrade
  _The common error message triggered by this change looks as follows:    > zsh: defining function based on alias `foo'   > zsh: parse error near `()'    See https://bugs.debian.org/871816 for more information._

**Comment by tleonhardt** [comment]
Ok, so your problem appears to be due to a bug in a specific version of **zsh** which has been fixed in newer versions of **zsh**.  

I would recommend trying to run your ``cmd2`` application using **bash** and/or finding a way to update to a newer version of **zsh**.

I'm going to close this issue because there does not appear to be any problems with ``cmd2`` involved.  Feel free to reopen it if you feel differently.  Good luck.
