### ISSUE TITLE
Handle readline not being installed

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#361]
Some calls into readline module are not wrapped in a ``try/except`` block and therefore cmd2 can crash with a ``NameError`` exception.

Also, we should print a warning in yellow if readline fails to import and give OS-specific instructions how to install it.

**Comment by tleonhardt** [comment]
As a potential aside note, but also as something which may reasonably fall within this Issue ...

``cmd2``'s current **colorize()** capability works on Linux and macOS but not on Windows because it uses simple old school ANSI color escape codes.

The more I think about it, it may be time to add a dependency on ``colorama`` and to refactor the existing ``cmd2.Cmd.colorize()`` method so that it works in a fully cross-platform manner including on Windows.

**Comment by anselor** [comment]
I've added colorama as a dependency on the autocompleter branch.
