### ISSUE TITLE
Replacing pyparsing with shlex

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#37]
Python's built-in "shlex" module for simple lexical analysis is probably good enough to handle our command-line parsing in cmd2 and it is implemented in C, so its performance would probably be a lot better than pyparsing, which is implemented in pure Python.

ANTLR and PLY also look like potentially superior alternatives to pyparsing, which is slow, dated, and at least in our case requires an overly-complicated grammar.

But shlex should be preferred since it is built-in to Python and not 3rd-party.

shlex:
https://docs.python.org/3.6/library/shlex.html

pyparsing:
http://pyparsing.wikispaces.com

ANTLR:
https://github.com/antlr/antlr4

PLY:
https://github.com/dabeaz/ply

This is a long-term "down the road" idea.

**Comment by tleonhardt** [comment]
@FedericoCeratto 
I've researched shlex a little bit and it looks like it could serve as a a viable replacement for pyparsing.  

The advantages of using shlex over pyparsing would be:

- Reduce dependency on 3rd-party modules which aren't built into the Python standard library
- Likely a significant performance boost in terms of CPU time to parse

But moving to shlex would necessitate a non-backwards compatible feature change in how we deal with comments.  Currently both Python-style ("#...") and C-style ("/* ... */") comments are supported.  If we switch from pyparsing to shlex, then we would only be able to support Python-style comments.  The usage of comments really only makes sense in scripts.

In your opinion, would this minor backwards incompatibility be acceptable?

**Comment by tleonhardt** [comment]
shlex is just a lexer, not a full parser.  So shlex is capable of doing a fine job of tokenizing the input.  But we would still need to write custom logic to properly parse the tokens.

**Comment by kotfu** [comment]
I have no experience with any of the parsing tools linked above, but in 30 minutes of trying to learn a bit about each one, I think PLY seems like the best fit for cmd2. ANTLR doesn't feel very python-ish, given that you use a java program to define the grammar and then have it auto-generate python code for you. shlex only tokenizes and would require us to write a custom parser. pyparsing is slow (for us, and maybe for others too). ply has a pythonesque interface, is well maintained, and doesn't require any C extensions.

**Comment by tleonhardt** [comment]
I think either ``PLY`` or ``shlex`` would be reasonable options, with ``PLY`` probably being the path of least resistance.

Regardless this issue will be somewhat of a pain to work on because it will involve two learning curves:
- First figuring out how ``pyparsing`` works along with how the current ``cmd2`` pyparsing-based parsing implementation functions
- Second learning how ``PLY`` works and how to re-factor the current ``cmd2`` parsing to use ``PLY`` instead of ``pyparsing``

On the other, hand, the performance benefits will likely be substantial - a factor of 5x or better is likely.  These performance improvements probably won't be very noticeable during pure human interaction, but for scripts and/or unit tests they will likely be dramatic.

**Comment by kotfu** [comment]
Created new branch `ply` for this work.

**Comment by kotfu** [comment]
Tried implementing it with ply, spent lots of time and got frustrated trying to make the pipe work.

Tried implementing it with shlex, and made rapid progress. I think I'm gonna switch horses and try and finish it just using shlex.

**Comment by tleonhardt** [comment]
@kotfu You should touch base with @kmvanbrunt since I know he was thinking of taking a stab at a silex-based implementation and had a lot of ideas for how to best proceed with that.

I like the idea of a shlex-based implementation for multiple reasons:

1. ``shlex`` is built into Python so we would remove a 3rd-party dependency
2. ``shlex`` is designed for parsing shell-like commands and that is exactly what we are doing
3. ``shlex`` is implemented in C so should hopefully be very fast

**Comment by kmvanbrunt** [comment]
@kotfu @tleonhardt 
I'll just dump core here. You may already know this stuff.

I found `shlex` to be very effective in the latest tab completion code I added.
Take a look at `tokens_for_completion()`. You could probably take the middle part of the function that parses out redirection/pipes and turn it into a common function that your tokenizer and the completion tokenizer use. That block of code works similar to how punctuation characters are treated in `shlex` when using Python 3.6 or greater: "any run of these characters (considered punctuation characters) is returned as a single token"

Just using the basic shlex.split() method was enough. It splits only on whitespace and properly handles quoted tokens. These settings don't restrict `shlex.wordchars` to ASCII and therefore allows us to support utf-8 command line arguments. If we only plan on supporting # for comments, then you can just set `comments` to True when calling split. I'm not sure why C-style comments were ever supported in cmd2. Continuing to do so will require custom parsing of the `shlex` tokens, which isn't hard, but its weird supporting C-style comments in a Python based CLI.

Your tokenizer function would be simpler than `tokens_for_completion()` since you can just print an error if the command line has an unclosed quote.

I hope some of that was helpful.

**Comment by kotfu** [comment]
I already saw `tokens_for_completion()`, it's what inspired me to try a `shlex` based implementation.

I easily solved the C and C++ style comments with a regular expression before calling `shlex.shlex()`. I'm gonna look at multi-line commands next, and I would like to continue to support them, because if you want to do any SQL, you pretty much need them.

My current strategy is to build a parser that passes all the existing unit tests, and then figure out how to integrate that parser into `cmd2.Cmd()`.

**Comment by tleonhardt** [comment]
I think your strategy of building a parser that passes all of the existing unit tests and then figuring out how to integrate it into ``cmd2.Cmd`` sounds like an excellent one.

**Comment by tleonhardt** [comment]
I'm very glad to hear that the ``shlex`` implementation is progressing nicely!  

I could take or leave the POSIX parsing support.  I'm happy with whatever you and @kmvanbrunt decide in regards to that.

For the multiline support, while I personally have never used it, I know that some of our end users do use it on a regular basis because we have gotten some interesting bug reports in the past related to that not interacting correctly in combination with other features.  So I would prefer to keep it in if it isn't too painful.  But in the end if it really makes maintenance a nightmare, then I wouldn't scream too badly about removing it.

**Comment by kmvanbrunt** [comment]
@kotfu 
I believe the unicode issue is solved if you set ``shlex.whitespace_split`` to True. Otherwise anything not in ``wordchars`` gets split into an individual token. So something like 'αβγδ' would become ['α', 'β', 'γ', 'δ']

Is there a danger in just having ``shlex`` split on whitespace to allow unicode support? We can always handle the punctuation characters like I did in ``tokens_for_completion()``. Plus the ``punctuation_chars`` argument to ``shlex`` wasn't added until 3.6 so I'm not sure if we can use it anyway.

**Comment by kotfu** [comment]
*@#&!*%. `ushlex` is python2 only. Maybe it's time for me to write a `shlex2` module...

**Comment by kotfu** [comment]
@kmvanbrunt `shlex.whitespace_split` solves the unicode issue, but introduces other problems, like:

- `command>output.txt` lexes as a single token, not three tokens
- `command |wc` lexes as two tokens, not three tokens
- `command arg;suffx` lexes as two tokens, not four

**Comment by tleonhardt** [comment]
@kotfu I don't believe we have ever advertised that we support unicode in command names, in fact I think we may say somewhere that we do not.  I'm not sure if that helps the parsing logic, but it might.

We do need to support unicode in command arguments (and command output).  But I don't think there is a hard rule that we need to support unicode in command names.  Of course if it is easy to do so, then great - I know we have a substantial base of users who have non-ASCII languages as their native language.

I'd recommend hopping on some sort of real-time chat or a phone call with @kmvanbrunt (maybe we should setup a Gitter or Slack channel for cmd2) since I know he has spent a lot of time working with ``shlex`` and might have some good ideas in regards to how to implement the parsing logic we need.

**Comment by tleonhardt** [comment]
On a positive note it sounds like there are some good unit tests if you caught all of those edge cases in the parsing logic that quickly ;-)

**Comment by tleonhardt** [comment]
When you parse with ``shell.whitespaces_split``, can it leave quotes in the tokens if they were there to start with?  If so, we could make a 2nd pass through each token and split in a different way and then strip quotes in the final tokenized output.

**Comment by kmvanbrunt** [comment]
@tleonhardt 
``shlex.whitespaces_split`` does leave quotes when used in non-POSIX mode. I use this feature a lot.
I also strip the quotes as you describe. ``tokens_for_completion()`` returns both versions of the tokens.

@kotfu 
The following cases are already handled by the second pass I make over the shlex tokens. Did you receive the function I emailed you? It performs a second pass on the ``shlex`` tokens and further splits on redirectors and terminators. It is basically a tweaked version of what I do in ``tokens_for_completion()``

- command>output.txt lexes as a single token, not three tokens
- command |wc lexes as two tokens, not three tokens
- command arg;suffx lexes as two tokens, not four

**Comment by kmvanbrunt** [comment]
@tleonhardt 
Unicode commands are not really supported unless the user overrides identchars.
``IDENTCHARS = string.ascii_letters + string.digits + '_'``

cmd has this requirement about commands:

> A command is parsed out of each line by collecting the prefix composed of characters in the identchars member.

**Comment by tleonhardt** [comment]
@kmvanbrunt Can you paste the function you refer to within this Issue?

**Comment by kmvanbrunt** [comment]
def split_on_punctuation(self, initial_tokens):
    """
    # Further splits tokens from a command line using punctuation characters
    # as word breaks when they are in unquoted strings. Each run of punctuation
    # characters is treated as a single token.

    :param initial_tokens: the tokens as parsed by shlex
    :return: the punctuated tokens
    """
    punctuation = [self.terminator]
    if self.allow_redirection:
        punctuation += REDIRECTION_CHARS

    punctuated_tokens = []

    for cur_initial_token in initial_tokens:

        # Save tokens up to 1 character in length or quoted tokens. No need to parse these.
        if len(cur_initial_token) <= 1 or cur_initial_token[0] in QUOTES:
            punctuated_tokens.append(cur_initial_token)
            continue

        # Iterate over each character in this token
        cur_index = 0
        cur_char = cur_initial_token[cur_index]

        # Keep track of the token we are building
        new_token = ''

        while True:
            if cur_char not in punctuation:

                # Keep appending to new_token until we hit a punctuation char
                while cur_char not in punctuation:
                    new_token += cur_char
                    cur_index += 1
                    if cur_index < len(cur_initial_token):
                        cur_char = cur_initial_token[cur_index]
                    else:
                        break

            else:
                cur_punc = cur_char

                # Keep appending to new_token until we hit something other than cur_punc
                while cur_char == cur_punc:
                    new_token += cur_char
                    cur_index += 1
                    if cur_index < len(cur_initial_token):
                        cur_char = cur_initial_token[cur_index]
                    else:
                        break

            # Save the new token
            punctuated_tokens.append(new_token)
            new_token = ''

            # Check if we've viewed all characters
            if cur_index >= len(cur_initial_token):
                break

    return punctuated_tokens

**Comment by kotfu** [comment]
More work pushed to **ply** branch. Only 5 unit tests don't pass. Still need to do aliases, shortcuts, and multiline. Will also need to do some refactoring and pruning of other existing code to better leverage the new parsing logic, i.e. `complete()`. But it feels like I'm over the hump.

**Comment by tleonhardt** [comment]
@kotfu Wow that is completely awesome!  I was hoping for a factor of 10x performance improvement, but it actually sounds like it will be significantly better than that.

Very nice work sir.  

Please feel free to reach out to @kmvanbrunt when it comes time to refactor logic related to ``complete()`` or other tab-completion methods, I'm sure he would be happy to collaborate with you on that.

**Comment by kotfu** [comment]
Question for @kmvanbrunt regarding aliases and multiline commands. Say I have a command called **alice** which is a multiline command. If I make an alias for **alice** called **bob**, is bob a multiline command too (even though it may not be listed in `cmd2.multilineCommands`)?

I think the answer should be yes. If so, the parsing logic should expand aliases before doing any processing to determine whether a command is multiline or not.

**Comment by kotfu** [comment]
Here's multiline commands in a nutshell. To the user, instead of <return> completing your entry of the statement, you have to have an unquoted semicolon (or two <return> characters in a row). If you are familiar with how SQL commands in the `mysql` command line program work, that's pretty much how they work in `cmd2`.

Internally, when the user presses <return> the parsing logic checks if the first word on the line is one of the multi-line commands. If it is, and if the terminator character is not found in the input, then `cmd2` changes the prompt, and lets the user keep typing. This repeats until the terminator character is found, after which we join all the lines together and then fully parse the whole thing.

**Comment by kotfu** [comment]
Closed by #370
