### ISSUE TITLE
Extract submenus into a new project

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#375]
The submenu feature is nice, but it's very complex. What if we extracted the submenu code into a new GitHub project at https://github.com/python-cmd2/cmd2-submenus, and packaged it in pypi as a separate wheel, something like cmd2-submenus. This would enable:

1. Easier maintenance of the core cmd2 module
2. Version dependency between releases of cmd2 and cmd2-submenus. If cmd2-submenus lags behind cmd2 features, users of both modules can make a decision whether they want to most current cmd2 capabilities, or submenu support.
3. Set a pattern for extensibility of cmd2 via additional packages instead of changes to the core.

I'm willing to take a crack at the extraction of the submenu code if there is interest in pursuing this proposal.

**Comment by kmvanbrunt** [comment]
What about the submenus not having access to ``self.command_parser``?

**Comment by tleonhardt** [comment]
I like the idea of extracting the submenu code into a new GitHub project underneath the python-cmd2 organization.  

Easier maintenance for the core of ``cmd2`` would be welcome.  But with being able make ``cmd2-submenus`` require a certain version of ``cmd2``, we could still maintain the Submenu feature, albeit at perhaps a somewhat slower pace.

I also like the concept of setting a pattern for extending ``cmd2`` via additional packages.  Features may come along which are very desirable for a certain subset of users which may not feel appropriate to incorporate within the core ``cmd2`` module and/or may add additional 3rd party dependencies which we don't want to levy on the core ``cmd2`` module.

**Comment by kmvanbrunt** [comment]
@kotfu 
What version of ``cmd2`` will this be tied to? You and I both have bugs where the submenu does not have access to a parent's attribute. In fact, starting with 0.8.4, submenu tab completion has been broken because of this.

**Comment by tleonhardt** [comment]
I would say tie it to the last version of ``cmd2`` where the Submenu feature worked well.

**Comment by kmvanbrunt** [comment]
I think I was able to fix both of the submenu issues with tab completion. I'll create a PR soon. Hopefully this will help with @kotfu's issue, too.

By the way, I still support the idea of moving submenus to its own project.

**Comment by anselor** [comment]
@kotfu  @kmvanbrunt 
Since it appears there are easy fixes for submenus we should probably just patch it up as is in 0.8.X.

As for the 0.9.X branche, I have an alternate idea for submenus. I think it's possible to present subcommands (argparse sub-parsers) in a way that it looks like submenus. 

Commands using argparse can be decorated to indicate they want to present as a submenu. When one of these commands is processed, we can save it and flag that we're navigating down a particular command. Help and tab completion would then only present that command's subcommands. If there are more layers of subcommands, that would get pushed on to the command navigation stack and the next layer of subcommands would be available. When executing a command, we can automatically prepend the preceding layers command/subcommands before parsing the command.

Command history can be separately maintained when we go into this state just like with submenus today.
the shared attributes stuff from the current implementation wouldn't be needed because everything would be running in a single Cmd instance.

**Comment by tleonhardt** [comment]
@anselor 
If you think the approach you discuss is variable, from an architectural perspective I like it a **LOT** better than the current approach which involves nested ``cmd2.Cmd`` instances.

**Comment by anselor** [comment]
I'm also pretty sure this could be done as a specialized subclass of cmd2.Cmd so it doesn't need to be part of the base implementation.

**Comment by kotfu** [comment]
I've extracted the submenu code into a new project at https://github.com/python-cmd2/cmd2-submenu. There is a new branch here `extract_submenu` with the submenu code deleted. The new submenu project isn't quite working yet, but I'm pretty sure I can make it happen.

**Comment by tleonhardt** [comment]
Are we good to close this issue now?  Or does more work need to be done in the other project?

**Comment by kotfu** [comment]
Let’s close it. I’ll open issues in the other project for what else needs to be done. I’ll also somehow add a note to the other project saying we are looking for a maintainer.
