### ISSUE TITLE
Modify ppaged() to look for PAGER environment variable

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#393]
On *nix-ish systems, a user can set the environment variable **PAGER** to be their preferred output paginator. We should modify `ppaged()` to use the contents of that environment variable before defaulting back to `less`.

**Comment by tleonhardt** [comment]
In order to make the ``ppaged()`` method works as intended, we had to be very careful about what pager we used and what flags were sent to it.  

Theoretically it is nice to allow a user to choose which pager they want to use with the **PAGER** environment variable.  However, this also gives end users to effectively break ``cmd2`` applications without knowing why.  

I think I would want something like a boolean variable in the ``cmd2.Cmd`` class which would allow ``cmd2`` applications to explicitly bypass using the **PAGER** environment variable to ensure consistent behavior.  Alternatively we could make the underlying command called by ``ppaged`` is a runtime settable parameter akin to the editor.
