### ISSUE TITLE
cmd2.onecmd() was not working after release 0.9.x

### ISSUE THREAD

**Issue by WSQi** [python-cmd2/cmd2#435]
cmd2.onecmd() was not working after release 0.9.x

It was still work as expected in 0.8.6
```
> py main.py somecommand
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "main.py", line 9, in main
    c.onecmd(' '.join(sys.argv[1:]))
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\cmd2\cmd2.py", line 1906, in onecmd
    funcname = self._func_named(statement.command)
AttributeError: 'str' object has no attribute 'command'
```

```
# main.py
import sys
import multiprocessing
from inc.Command import Command


def main() -> None:
	c = Command()
	if len(sys.argv) > 1:
		c.onecmd(' '.join(sys.argv[1:]))
	else:
		c.cmdloop()


if __name__ == '__main__':
	multiprocessing.freeze_support()
	main()
```
```
# Command.py
import cmd2 as cmd


class Command(cmd.Cmd):
	...
```

**Comment by tleonhardt** [comment]
@WSQi 
The ``onecmd()`` method was never intended to be user-facing and because of that we made a change regarding the type of argument it takes.  It now takes a ``Statement`` instance from **parsing.py** instead of a ``str``.

For the sort of thing you are trying to do, we recommend that you use the ``onecmd_plus_hooks()`` method instead of ``onecmd()`` to run a single command or ``runcmds_plus_hooks()`` if you wish to run multiple commands.

``onecmd_plus_hooks()`` does the following:
1. Parses the single string argument passed to it as a cmd2 command, including arguments and possible redireciton/pipeing
2. Runs all of the application lifecycle methods like ``precmd``, ``postcmd``, etc. at the proper time
3. Handles redirection and/or piping if enabled
4. Measures command execution time if that feature is turned on
5. Runs the actual command using ``onecmd``
6. Deals with exceptions

If for some reason you really don't want all of the extra stuff provided by ``onecmd_plus_hooks``, then you can slightly modify your ``main()`` to parse the string into a ``Statement`` like so:
```Python
def main() -> None:
	c = Command()
	if len(sys.argv) > 1:
		c.onecmd(c._complete_statement(' '.join(sys.argv[1:])))
	else:
		c.cmdloop()
```

**Comment by WSQi** [comment]
@tleonhardt Thanks for clarification, I will mark the issue as Closed.

**Comment by WSQi** [comment]
@tleonhardt For suggestions, maybe the [cmd2 Docs](https://cmd2.readthedocs.io/en/latest/integrating.html?highlight=onecmd_plus_hooks) could be updated with more examples.

Looks like the code could be modified to the following without using package's private function:
```python
def main() -> None:
	c = Command()
	if len(sys.argv) > 1:
		c.runcmds_plus_hooks([" ".join(sys.argv[1:])])
	else:
		c.cmdloop()
```
