### ISSUE TITLE
onecmd should accept a raw string

### ISSUE THREAD

**Issue by ksunden** [python-cmd2/cmd2#464]
I have commands that I want to run without the hooks as strings, but trying to run `onecmd` directly fails because `command` and `args` to be in the namespace.

This is inconsistent with the `cmd` standard library module.

**Comment by ksunden** [comment]
workaround:
```
from cmd2 import parsing
...
parser = parsing.StatementParser(terminators=[';'])
cmd = parser.parse(cmd)
self.onecmd(cmd)
```

Note: explicit setting of terminators required due to #463

**Comment by tleonhardt** [comment]
Hi Kyle,

Thanks for reporting this issue. 

 In general, we **strongly** encourage developers to use either ``onecmd_plus_hooks`` or ``runcmds_plus_hooks`` because they handle a bunch of stuff in a consistent manner including:
- multiline commands
- calling "hook" functions
- exception handling
- redirection/piping
- command timing (if enabled)

However, ``cmd2`` does strive to be a compatible and consistent extension of ``cmd`` and only in the most exceptional of circumstances do we intentionally deviate from that.  So I think it would probably be beneficial if we have some sort of *fallback* mode for gracefully handling the case where a developer calls ``onecmd`` directly with a ``str``. 

@kotfu @kmvanbrunt 
Do either of you have an opinion on this one?

**Comment by tleonhardt** [comment]
@ksunden What do you think about the possible solution in PR #465?

**Comment by ksunden** [comment]
That's more or less what I had in mind.

**Comment by kotfu** [comment]
I like the fallback to `str` as implemented in the PR. This gives `onecmd_plus_hooks`, `runcmds_plus_hooks`, and `onecmd` the exact same behavior on multiline commands: if you pass a string to one of these functions, and it happens to be an incomplete multiline command, `cmd2` is going to prompt for more input. Perhaps not the most desirable behavior, but it's consistent. I say we merge it.
