### ISSUE TITLE
Update Contributor's Guide to recommend using a virtualenv

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#471]
To encourage good best practices, we should update the [Contributor's Guide](https://github.com/python-cmd2/cmd2/blob/master/CONTRIBUTING.md) to encourage developers to use either a [virtualenv](https://virtualenv.pypa.io/en/stable/) or [pipenv](https://docs.pipenv.org/).  This article has a good overview:
http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by kotfu** [comment]
I think we should also consider adding instructions showing how to install, use, and test against multiple python versions. We should have instructions for both `conda` and `pyenv`.

**Comment by tleonhardt** [comment]
Totally agree about adding instructions showing how to install, use, and test against multiple Python versions.

I haven’t used it yet, but from what I have read ‘’pipenv’’ sounds like a better version of ‘’pyenv’’ that also works on Windows.  I use and like ‘’conda’’.  Are you familiar with ‘’pipenv’’ at all?

**Comment by kotfu** [comment]
No, but from a quick look at the web site, it appears ‘pipenv’ is a better
‘virtualenv’, i.e. it creates python environments. It doesn’t appear to let
you run multiple versions of python, i.e. python3.4 and python3.5. ‘pyenv’
downloads, compiles, and let’s you use multiple versions of python at the
same time. As best I can tell,

Conda = pyenv + virtualenv
Conda = pyenv + pipenv

Jared


On July 24, 2018 at 10:08:00 PM, Todd Leonhardt (notifications@github.com)
wrote:

Totally agree about adding instructions showing how to install, use, and
test against multiple Python versions.

I haven’t used it yet, but from what I have read ‘’pipenv’’ sounds like a
better version of ‘’pyenv’’ that also works on Windows. I use and like
‘’conda’’. Are you familiar with ‘’pipenv’’ at all?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/python-cmd2/cmd2/issues/471#issuecomment-407626987>,
or mute
the thread

**Comment by tleonhardt** [comment]
Ok, looking more pipenv is really just a nicer replacement for virtualenv which combines some pip functionality and can work well in combination with pyenv:  
https://docs.pipenv.org/

In that case I like your idea of showing instructions for both pyenv and conda.  Perhaps also using pipenv in combination with pyenv.

**Comment by teto** [comment]
Let's not add to the maintainance burden. The ecosystem evolves fast and "best practice" kinda depend on your surroundings. For instance I could quote "nix" along with conda.

**Comment by tleonhardt** [comment]
@teto What specifically are you suggesting?

The basic idea of updating the Contributor's Guide to recommend using a virtualenv seems like it has been best practice for a long time and will likely remain so for the foreseeable future.  

Perhaps recommending ``pipenv`` is debatable at this point.  But I think covering ``peen`` and ``conda`` are good things for users.

We didn't consider adding a guide for ``*nix`` for several reasons:
1. How exactly to do it varies greatly from one ``*nix`` environment to another
1. ``*nix`` users tend to be extremely knowledge about how to administer their own systems and generally don't need the help

**Comment by tleonhardt** [comment]
I forgot to mention that installation using ``*nix`` package managers is not in any way mutually exclusive with using a virtualenv and it is a recommended best practice to use a virtualenv env on ``*nix`` environments.

**Comment by teto** [comment]
My concern is just that this is not a consideration specific to cmd2 and that it adds to the maintenance burden. But if the maintainers are fine with it than no problem.

**Comment by tleonhardt** [comment]
You have a valid point that this is in no way specific to ``cmd2``.  But in attempt at making it easy to onboard new developers/maintainers we strive to have a good Contributor's Guide which can help hold the hand of someone new to Python unit testing and code coverage analysis, Sphinx documentation, **pip** package installation, etc.  It does increase the maintenance burden for existing developers slightly, but hopefully not too much.
