### ISSUE TITLE
Reduce or eliminate redundant definitions of dependencies

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#486]
We currently have dependencies specified in multiple files. Ideally they would only be specified in a single place. I think the right place for these is `setup.py`, but we could/should have a discussion about the single place.

`tox.ini` is the big offender here. Each environment specifies a list of dependencies to install in order to test the package. Instead of:

`deps = 
  mock
  pytest
  pytest-cov
  pytest-mock
`

We should have:

`extras = dev`

which instructs tox to install all the dev dependencies from `setup.py`. `setup.py` is already platform and python version smart about which dependencies are actually needed.

There are some other potential files to examine, but they just install `tox`, so maybe they could be forgiven, but if we can figure out a way...

- appveyor.yml
- travis.yml

**Comment by tleonhardt** [comment]
``setup.py`` does seem like the appropriate place to be the "source of truth" regarding dependencies

**Comment by tleonhardt** [comment]
The fine-grain configuration of the dependencies in **tox.ini** originated back when the tests were a lot slower prior to converting the parser  from ``pyparsing`` to ``shlex`` and we didn't want to run code coverage for every single configuration because that took a lot of time.  The fact that some versions of Python required ``mock`` and others didn't also played a role.

Now that the tests run much faster, this can probably be simplified.  But I would recommend not doing ``extras = dev`` since the **dev** set of dependencies installs a bunch of developer tools which aren't required for testing.  If we are going that route, I could create a set of test dependencies in **setup.py**.  Actually we had that until recently when I deleted it because we weren't using it ;-)
