### ISSUE TITLE
Fix VSTS build to run `tox` instead of `pytest`

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#488]
As currently configured, the VSTS build installs dependencies and runs pytest and codecov. This tries to install packages into the container default python, which fails. We should switch this to run `tox` instead, which will install packages in virtualenvs.

**Comment by kotfu** [comment]
We may need/want a special tox environment for VSTS on macOS, so that we can get the test results out in the junit format that VSTS understands.

**Comment by tleonhardt** [comment]
The Hosted macOS builds are a preview feature in VSTS and the fact that I'm using the system default Python is a side-effect of the fact that the last time I checked, they hadn't populated the VSTS package cache for the Hosted macOS build agents which can be used to build/test with multiple versions of Python in virtualenvs based on the ``python.version`` variable and changing the build parallelsm to Multi-configuration.  So basically VSTS has their own way of dealing with this which just isn't fully implemented yet for mac (but currently works on Linux and Windows build agents).

But honestly if we can get it to work with ``tox`` then that would be fine and more symmetric with our other CI systems.

**Comment by tleonhardt** [comment]
I fixed the VSTS configuration for now so that it doesn't fail.  I don't install the full-blown [dev] dependencies from setup.py because something in there was causing an issue (maybe **invoke**, but not 100% sure).

**Comment by tleonhardt** [comment]
Since this ticket was originally created, the VSTS build for macOS has been modified in a couple substantial ways:
1. It is now controlled by the [azure-pipelines.yml](https://github.com/python-cmd2/cmd2/blob/master/azure-pipelines.yml) YAML file in the root of the ``cmd2`` GitHub repo.
1. It now runs the tests on 4 different versions of Python using Azure Pipeline's build-in matrix strategy.

VSTS is sort of particular in the way it does things.  I searched for other open source projects that might be using ``tox`` on VSTS and the only one I could find is the [tox](https://github.com/tox-dev/tox) project itself.  Their approach is quite complicated.  

If we can find a simpler way to use ``tox`` on VSTS that would be great.  If not, then I don't view it as essential, though it would be nice.

**Comment by tleonhardt** [comment]
I looked into this more and it should be very do-able.  I created PR #589 for it.
