### ISSUE TITLE
Question: multiline command args with  matching quote on another line?

### ISSUE THREAD

**Issue by space88man** [python-cmd2/cmd2#495]
Is it possible to configure cmd2 to have the closing quote on another line ('embedded newline in args'):

my_command  is a multiline command

Expected behaviour
my_command  'This is a long arg broken over two
lines';

self.argv[1] = 'This is a long arg broken over two\nlines'

Currently the parser shows "ERROR: Invalid syntax: No closing quotation"

**Comment by tleonhardt** [comment]
@kotfu How difficult do you think this would be to fix?

I verified that the old pyparsing-based parsing code used prior to version 3.0 did parse multiline commands where a quoted portion spanned multiple lines correctly.

**Comment by kotfu** [comment]
Agree that @space88man has described the expected behavior, and therefore we have a bug. Changed the tag (question -> bug). Had a quick look at the code, won't be a super easy fix, but definitely doable. Also super glad we have very good unit tests on this part of our code.

Here's the current steps for parsing user input:

1. get user input
2. strip comments
3. expand shortcuts and aliases
4. use `shlex` to split on whitespace (this is where the error found by @space88man is coming from)
5. do additional word splitting to account for output redirection, etc.
6. look for command terminators
7. look for output redirection and piping
8. check if the command is multiline, if it is and if we don't have a terminator, go back to step 1 to get more user input.

To fix this bug, we need to do step 8 before we run anything through `shlex`.
