### ISSUE TITLE
Consider best path forward for full deprecation of the old-style hook methods

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#512]
The [0.9.4](https://github.com/python-cmd2/cmd2/releases/tag/0.9.4) release came with a set of new-style lifecycle hook methods which support a plugin framework and marked some but not all of the old-style lifecycle hook methods as deprecated and to be deleted in a future release.

We cannot deprecate *all* of the old-style lifecycle hook methods without abandoning 100% API compatibility with ``cmd`` because a couple of them were introduced by ``cmd`` and are thus required for compatibility with ``cmd``.  It seems a little awkward to say "for these hooks do it the old way, but these other ones have to be done the new way".

One way or another, I would very much like to stabilize the API before the 1.0 release and keep it as stable as possible after that point (well at least not remove stuff on any sort of regular basis).  I'm not entirely sure what the best path forward is, but I think we should all agree on it and do a good job of communicating it to end users.  A few possibilities include all of the following, some of which would be somewhat "extreme" and we should think carefully about:

* Deprecate the **precmd()** and **postcmd()** hooks introduced by ``cmd``
    * Pro: Would have a single consistent way of dealing with lifecycle hooks    
    * Con:  Would deviate from ``cmd2`` being a strict enhancement of ``cmd``
* Revert to the old-style hooks
    * Pro: Would have a single consistent way of dealing with lifecycle hooks
    * Con: Would dramatically reduce the ability for plugins to call lifecycle hooks
* Use new-style hooks where possible and support the minimal old-style hooks required for ``cmd`` compatibility
    * Pro: Compatibility with ``cmd`` and with the new ``cmd2`` plugin framework
    * Con: Slightly awkward way  of having to support two different ways of doing something similar
* Don't deprecate any of the current hook methods
    * Pro: No breaking of backwards compatibility for existing apps
    * Con: Maintenance headache of having two different ways of doing something similar

@kotfu @kmvanbrunt What are your thoughts?

**Comment by kmvanbrunt** [comment]
> Deprecate the **precmd()** and **postcmd()** hooks introduced by `cmd`

@tleonhardt Does this mean replace them with new-style hooks?

**Comment by tleonhardt** [comment]
@kmvanbrunt I believe that sufficient new-style hooks exist already and that the old ones are effectively redundant but in place for compatibility.

Btw, I’m not advocating any of these particular solutions.  I can’t really think of a “perfect” solution.  But I thought maybe it would be beneficial to begin a conversation because maybe someone else has a bright idea 😀

**Comment by kmvanbrunt** [comment]
@tleonhardt My mistake. I didn't see `_precmd_hooks` and `_postcmd_hooks`.

I'm OK moving away from cmd compatibility since we've already done that in other areas. Do we know how often people convert from existing `cmd` apps?

**Comment by kmvanbrunt** [comment]
If `precmd()` and `postcmd()` go away, what about `preloop()` and `postloop()`?

Another option is to not deprecate any of the current hook methods. The plugin hook system is available for those who need it, but basic apps can continue to just override the current methods.

**Comment by kmvanbrunt** [comment]
Since we actually inherit from **Cmd**, I guess it doesn't make sense to totally ignore its methods. So for that reason, I think we need to keep calling `precmd()`, `postcmd()`, `preloop()`, and `postloop()`.

Is there any reason to deprecate our current hook system?

@kotfu What was the reason you wanted to deprecate certain functions? Perhaps I'm missing the pros of that decision. What would be the downside of leaving those methods while also supporting the plugin based hooks?

**Comment by tleonhardt** [comment]
I have no data to know how often people convert from existing ``cmd`` apps.  My guess would be more often than we know of.  In my extremely limited purview, I'm aware of at least one product that got converted from ``cmd`` to ``cmd2``, but I'm only aware of about 4 ``cmd2`` products, so I'd say somewhere around 1/4 or 1/3 would be a reasonable guess.

``preloop()`` and ``postloop()`` are somewhat logically different from the other lifecycle hooks in that these two are run once per application invocation, whereas the others are run once per command.

I will add the additional option you called out to the list of options in the Issue description.

I think the basic reason for deprecating the current hook system is that it is confusing for new users if we have two separate ways of doing the same thing.  Additionally, it is potentially painful to document and maintain two different ways of doing the same thing.

**Comment by kotfu** [comment]
As currently implemented in master:

- All 'hook' methods called by `cmd.Cmd` are called by `cmd2.Cmd`. This includes `preloop()`, `postloop()`, `precmd()`, and `postcmd()`.
- earlier versions of `cmd2` added additional hook methods (`preparse()`, `postparsing_precmd()`, and `postparsing_postcmd()`) which are now deprecated, because they are replaced by a more flexible and sophisticated system.
- New system which allows you to register multiple methods to be called at given points in the command lifecycle. These methods can be called whatever you want, as long as you register them properly.

This approach aligns with the third option proposed in this issue.

@kmvanbrunt I deprecated the old `cmd2` hooks because:

- `preparse()` is deceptive because if you have a multi-line command that actually spans multiple lines, `preparse()` will not receive all the user input. We have to parse to know if a) it's a multi-line command and b) if we have a command terminator.
- `postparsing_precmd()` is nearly identical to `precmd()`, just that the command timer hasn't started.
- `postparsing_postcmd()` has a terrible name, and is nearly identical to `postcmd()`, it just gets called after the timer stops

I feel pretty strongly that we should do all that we can to maintain backwards compatibility with `cmd.Cmd`. To my knowledge, the only thing from `cmd.Cmd` that we don't support is `identchars`, which could be implemented as a plugin if the user is willing to sacrifice other advanced `cmd2`-only features like tab completion and full unicode support.

I agree that the currently implemented plugin approach is a bit awkward, but it retains backwards compatibility while offering future flexibility. Developers only need to use the new system of hooks when building a plugin which requires hook functionality, or for a few edge cases (i.e. `postcmd()` is a long running function, and you are timing the commands, but don't want the clock time for `postcmd()` to be included in the timer). So for the vast majority of users, they can use the same hook methods provided by `cmd.Cmd`, and everything just works when they move to `cmd2`.

I believe the current implementation strikes the right balance, and I vote that we leave it as currently implemented, which is option 3 in the top of this issue.

**Comment by kmvanbrunt** [comment]
@tleonhardt Thanks for opening this discussion. It very much reflected the questions I had about the new hooks as well as deprecation of the old way.

@kotfu Thank you for clarifying. I understand the new system better now and will begin migrating my own tools to use it.

I'm OK with option 3 as well.

**Comment by tleonhardt** [comment]
Ok, since both of you like Option 3 which is to leave it like it currently is, I am going to close this issue.  I'm fine with the way it is, I just thought better to have an explicit conversation now rather than later.
