### ISSUE TITLE
help_xyz is not invoked when do_xyz is decorated with @with_argparser(xyzparser)

### ISSUE THREAD

**Issue by faraazc** [python-cmd2/cmd2#523]
help_xyz is not invoked when do_xyz is decorated with @with_argparser(xyzparser).

```Python3
    def help_xyz(self,):
     pass

    @with_argparser(connectParser)
    def do_xyz(self, args):
     pass
```

**Comment by faraazc** [comment]
I see below issue is somewhat related. If so some expert can close this.
https://github.com/python-cmd2/cmd2/issues/515

**Comment by tleonhardt** [comment]
While this is somewhat related to #515 and should probably be worked at the same time, it is logically a different problem.

@faraazc Thanks for reporting this issue.

This should be fixed, or for some reason if it is really difficult to fix, then at a minimum we should document the limitation.

**Comment by tleonhardt** [comment]
Any potential code fix for this Issue would be problematic in multiple ways:
* First, if a user types *foo -h* for a command **foo** which uses one of the ``argparse`` decorators, it wouldn't go through the ``help_foo`` function, but ``argparse`` would print its own usage statement.
* Secondly, and probably more importantly, it wouldn't deal at all with the case of running *foo bar -h* where **foo** is a command with subcommands and **bar** is one of those subcommands because ``cmd`` has no concept of subcommands.

We would rather encourage users to learn the ``argparse`` API and use it to its fullest. For instance, they could easily override a parser's or subparser's print_help() command instead.

For that reason, we will add documentation making it explicit that ``help_xyz`` will not be invoked for help when ``do_xyz`` is decorated with one of ``cmd2``'s ``argparse`` decorators.  We will also try to add links to relevant ``argparse`` documentation and examples of best practices.

**Comment by faraazc** [comment]
@tleonhardt. I agree with you..Thanks for describing the alternate solution..You can proceed to close this issue once the documentation is updated with the limitations and with the alternate solution.
