### ISSUE TITLE
@with_category discarded

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#552]
I don't know if it's a cmd2 problem or with my code.

There are some member functions for which I have:

```
    @is_loaded
    @with_category("mptcp")
    def do_list_mptcp_connections(self, *args):
         print("john doe")
```
with
```
def is_loaded(f):
    """
    Decorator checking that dataset has correct columns
    """
    def wrapped(self, *args):
        if self.data is not None:
            return f(self, *args)
        else:
            raise mp.MpTcpException("Please load a pcap with `load_pcap` first")
        return None
    return wrapped
```

These functions don't appear in the "mptcp" category. If I remove the is_loaded decorator, they do appear. I tried swapping the order of decorators but either way the function is not listed.

**Comment by anselor** [comment]
When you decorate a function you are replacing a function with a wrapper function that adds additional behavior before/after calling your function. Because of this, the function that is actually in the object is no longer the original function. It won't have the original function's name or attributes.

To get around the problem functools.wraps copies this information so that the original function's metadata gets presented.

Try adding:
`
@functools.wraps(f)
def wrapped(....
`

**Comment by tleonhardt** [comment]
@anselor Actually It looks like we accidentally forgot to use ``@functools.wraps`` in the ``with_category`` decorator as well.  We will need to fix that.

**Comment by anselor** [comment]
@tleonhardt We don't need to use `functools.wraps` on because `with_category` doesn't actually wrap the function in question. It adds an attribute to the passed-in function and passes it through.

**Comment by tleonhardt** [comment]
Oh, I just looked at the implementation very quickly.  Oh if it is just mutating the existing function/method and not returning a different one, then we should be fine.

**Comment by tleonhardt** [comment]
@teto Does adding the ``@functools.wraps`` decorator to your code as @anselor suggested solve the problem for you?  If so then I would like to close this Issue.

**Comment by teto** [comment]
solved it thanks !
