### ISSUE TITLE
A 'signal only works in main thread' Error during startup

### ISSUE THREAD

**Issue by bhairav13** [python-cmd2/cmd2#584]
In my script, I start Cmd2 under a separate thread.  This was fine until Cmd2 added signal catching support in some of the latest versions.  Now, when starting up the script, I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<redacted>/lib/python3.6/site-packages/cmd2.py", line 2875, in cmdloop
    self.preloop()
  File "<redacted>/lib/python3.6/site-packages/cmd2.py", line 1516, in preloop
    signal.signal(signal.SIGINT, self.sigint_handler)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

Apart from changing my script (which is a big change), is there anyway to by-pass the signal handling?  I don't really care for the signal handling as I take care of it internally in my script anyway.

Thanks.

**Comment by tleonhardt** [comment]
@bhairav13 
If you use the **cmdloop** method of ``cmd2.Cmd``, then that provides a full-blown REPL for your application and it assumes it is running in the main thread.

If you wish to manage your own event loop and/or REPL then that is fine and you can still use ``cmd2`` and get most of the benefits of using ``cmd2``.  However, in that case our intent has been for you to not use **cmdloop** since you are then responsible for managing the main loop yourself and you should be using either **onecmd_plus_hooks()** or **runcmds_plus_hooks()** instead. 

Please see the section in the ``cmd2`` documentation about [Integrating cmd2 with external tools](https://cmd2.readthedocs.io/en/latest/integrating.html) for more information.

**Comment by tleonhardt** [comment]
Alternatively, a potentially quick and easy solution would be for your to override the **cmdloop** method in your class which derives from ``cmd2.Cmd`` and simply copy the base method and then delete the sections of code which first setup the signal handler and later restore it.

**Comment by bhairav13** [comment]
Thank you @tleonhardt.  I was thinking of doing the same thing you suggested in your second comment.  Just wasn't sure if it would create problems down the road :) (when more modifications are made to the base Cmd2 code).

I'll give it a try in any case.  Thank you for all those pointers.

**Comment by bhairav13** [comment]
Thanks.  I only use intro banner from your list - so I will consider that method as well.

Also, if I may suggest another approach ...

In cmdloop, if you were to call separate methods for setting up and restoring the signal handlers (and that's all these methods would do), then the subclass of Cmd2 could easily override those methods and make them do nothing.  That way, any other updates to base cmdloop code could still be updated with new version updates without having to worry about mirroring those changes back into the subclass cmdloop.

**Comment by tleonhardt** [comment]
@bhairav13 Your suggested approach seems pretty reasonable and clean to me.

@kmvanbrunt @kotfu Do either of you have any thoughts on adding a couple methods called something like **setup_signal_handler** and **restore_signal_handler** so that these can be overridden according to the needs of particular applications?

**Comment by kmvanbrunt** [comment]
@bhairav13 @tleonhardt 
I don't have a problem with this approach, but it needs to be noted that removing cmd2's signal handler will alter its behavior. For instance Ctrl-C will no longer cancel the command being typed like Bash does.

Also, this approach is being implemented solely to support a case where cmdloop() isn't being run in the main thread despite the documentation saying:

> However, there are some limitations to this way of using cmd2, mainly that cmd2 owns the inner loop of a program. This can be unnecessarily restrictive and can prevent using libraries which depend on controlling their own event loop.

Should the docs be updated to be less restrictive?

**Comment by kmvanbrunt** [comment]
@tleonhardt I honestly can't think of any other use cases for this. Adding the methods also won't fix the crash until the user overrides them. So out of the box, **cmd2** still crashes. How do you document such a thing? I'd hate to see a docstring that says, "If these functions crash your code, override them with **pass**."

@bhairav13 I realize your code is already designed and written, but what was the initial reason for having the main thread not be the CLI?

**Comment by kmvanbrunt** [comment]
@tleonhardt @bhairav13 What if we check if cmd2 is the main thread before setting the signal handler?

**Comment by tleonhardt** [comment]
Yes I really like your idea of having **cmdloop** check if it is running in the main thread before doing anything related to signal handlers.  I think that sounds like a clean approach which should be reasonable for all use cases I can think of.

**Comment by bhairav13** [comment]
I whole-heartedly agree on checking for main thread before setting the signal handler.  Definitely a much cleaner approach.  That way, the signal handler setting would not even be invoked (and rightly so, since it is being run in the non-main thread, where it is not supported).

To answer your question @kmvanbrunt - My code does a very long-running task when it first gets kicked off.  Eventually, it settles down, but I didn't want to wait that long to give the user the command line access.  Hence, I made the CLI into a thread while the main activity continued behind the scenes.

**Comment by kmvanbrunt** [comment]
@bhairav13 Does the long-running task need to reach a minimum point before the CLI is started or would you say the CLI is fairly independent of this start-up task? Also, what happens in your application if the user types **quit**? Does the whole application, including the start-up task, close?

I'm asking these questions because I'm still not sure why the long-running task can't be its own thread that starts before you call `cmdloop()`. Without seeing the code I'm only guessing and perhaps there are valid reasons for your design. However, user interfaces typically should be the main thread and in the case of **cmd2** you are actually missing out on some features by not having it run in this fashion.

Regardless, we have implemented the proposed fix to prevent the crashing you were experiencing so you should be good to go once it's merged in.

**Comment by bhairav13** [comment]
@kmvanbrunt -  I agree with you that CLI should be on the main thread.  Unfortunately, I had started without it first and it was easier to make it a thread after-the-fact.  I will certainly look at re-working my code to make the CLI in the main thread.  Just requires a lot of testing that I currently lack the time for :)

Thanks again to both of you for considering the issue and implementing the fix.
