### ISSUE TITLE
ACArgumentParser isn't iterable

### ISSUE THREAD

**Issue by teto** [python-cmd2/cmd2#591]
at some point in my code I have
`            subparser = subparsers.add_parser(protocol, parents=[temp, super().default_parser()],`
with one of the parent parser being a ACArgumentParser.
It seems like argparse.ArgumentParser is supposed to be iterable as it can be used in Parents but ACArgumentParser isn't:
```
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/plot.py", line 310, in default_parser
    parser = super().default_parser(*args, **kwargs)
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/plot.py", line 88, in default_parser
    add_help=False,
  File "/nix/store/8mnvac3y9ss4if5q4qi4nkah79pz8lca-python3.6-cmd2-0.9.6/lib/python3.6/site-packages/cmd2/argparse_completer.py", line 995, in __init__
    super().__init__(*args, **kwargs)
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/argparse.py", line 1656, in __init__
    for parent in parents:
TypeError: 'ACArgumentParser' object is not iterable
```

**Comment by tleonhardt** [comment]
``ACArgumentParser`` inherits from ``argparse.ArgumentParser`` and exists mostly to override a few methods to provide better default help messages.  It shouldn't break any existing behavior since for overridden methods a small tweak is made and then the super-class method is called.

@teto From your error message, it looks like you passed in a single ``ACArgumentParser`` for **parents** but **parents** needs to be a list or other iterable.  Can you double check that this isn't a simple error on your end?

**Comment by teto** [comment]
I haven't found the error yet but it does seem like on my part.

**Comment by tleonhardt** [comment]
@teto Just curious, what was it?
