### ISSUE TITLE
Redirecting pyscript with app() commands closes cmd2

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#613]
I have a pyscript with 1 line:
`app('help')`

If the script is run like: `pyscript script.py > out.txt', then cmd2 closes.

If a second line is added as shown below and the script run as before, then an exception prints before cmd2 exits.
`app('help')`
`app('help')`

Exception that prints:
> Traceback (most recent call last):
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 1716, in onecmd_plus_hooks
>     stop = self.onecmd(statement)
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 2003, in onecmd
>     stop = func(statement)
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 259, in cmd_wrapper
>     return func(instance, args)
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 2591, in do_help
>     self._help_menu(args.verbose)
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 2640, in _help_menu
>     self.poutput("{}\n".format(str(self.doc_leader)))
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 601, in poutput
>     self.decolorized_write(self.stdout, msg_str)
>   File "/home/user/PycharmProjects/cmd2/cmd2/cmd2.py", line 579, in decolorized_write
>     (self.colors.lower() == constants.COLORS_TERMINAL.lower() and not fileobj.isatty()):
> ValueError: I/O operation on closed file
> EXCEPTION of type 'ValueError' occurred with message: 'I/O operation on closed file'

**Comment by tleonhardt** [comment]
I did a little regression testing and this bug was not present in the 0.8.9 release and is present in the 0.9.0 release.  So I believe it was introduced when [pyscript_bridge.py](https://github.com/python-cmd2/cmd2/blob/master/cmd2/pyscript_bridge.py) was created.

This bug isn't specific to the ``pyscript`` command, it is reproducible whenever a ``cmd2`` command is called with ``py`` and redirected; thus the following also quits the ``cmd2`` app:
```sh
(Cmd) py app('help') > out.txt
(py37) ✔ ~/src/cmd2/examples [master|…2]
```

However, running a non-cmd2 command with ``py`` does NOT exit the ``cmd2`` app:
```sh
(Cmd) py print('hi') > out.txt
(Cmd) !cat out.txt
hi
```

Also, the bug only applies to file redirection and not to pipes:
```sh
(Cmd) py app('help') | grep alias
alias  help     ipy   macro  pyscript  set    shortcuts
(Cmd)
```
