### ISSUE TITLE
Investigate potential StdSim and/or ByteBuf improvements

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#654]
The `StdSim` and `ByteBuf` classes were initially created as a convenient hack for use in unit and transcript testing with little to no thought given to factors like performance.  However, ``StdSim`` is now used by *pyscript_bridge.py* and hence by the **py**, **pyscript**, and **ipy** commands.

Issues that should be investigated include the following:
1. `ByteBuf` uses an immutable `bytes` object as a buffer to store text in the inner buffer.  If a lot of data gets sent here, constantly recreating new versions might be inefficient.  We should consider replacing it with some mutable type like a `bytearray`.
1. `StdSim` should probably behave like it's inner_stream. 
    * If the `inner_stream` is a `_io.TextIOWrapper` like `sys.stdout` typically is, then `StdSim` should provide the `buffer` interface.
    * If the `inner_stream` is a _`io.BufferedWriter` like a file opened in binary mode, then no `buffer` interface would be provided.
    *  In both cases, the `write` method should behave like the inner stream.
        * In the text case, `write(`) should accept strings, and in the binary case, bytes.

These changes will support wrapping `stdout` no matter what type of stream it is.

**Comment by kmvanbrunt** [comment]
After further thought, I think adding support for binary streams won't be necessary since **cmd2** assumes `stdout` is a text stream in all of its code.  That's why we call `self.stdout.write()` with a string. If we support binary streams, then these calls would need to be changed to encode the string into bytes before calling write. In a terminal application, I can't think of a good use case for that.

I did make some other enhancements to the `StdSim` class that I will create a PR for and close this ticket. After these are merged in, I believe `StdSim` to be in a good state.
