### ISSUE TITLE
Consider what output the pyscript is capturing in its StdSim objects

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#659]
**Question 1**
When we redirect a command, any output in **postparsing** and **cmdfinalization** hooks is not included in the redirected output. However, any output in **precmd** and **postcmd** hooks is redirected.

To be consistent, should an `app()` call in a **pyscript** capture this same output and exclude the **postparsing** and **cmdfinalization** hooks? Right now `app()` captures it all for `CommandResult.stdout`.
 
**Question 2**
Consider the command: `app('help > out.txt')`

What is the expected result?
1. `CommandResult.stdout` contains the output of the **help** command 
2. `CommandResult.stdout` is empty and `CommandResult.stderr` to contain text only if an error occurred redirecting output

Assume both cases do write the output of **help** to **out.txt** if no error occurred.

**Comment by kotfu** [comment]
Re question 1, I think output capture should be the same when inside a **pyscript** as it is when outside. Since it doesn't capture **postparsing** and **cmdfinalization** normally, I don't think it should capture it when using `app()`.

Re question 2, I vote for expected result 2. If you redirect output, it shouldn't also show up in `CommandResult.stdout`. If you want it to go to the file and to `CommandResult.stdout`, do `app('help | tee out.txt)` instead.

**Comment by kmvanbrunt** [comment]
@kotfu Those are my views as well.

As far as question 2 goes, that is our current behavior. I just wanted to confirm that's what people expected.

I like your suggestion to use **tee**. My idea was to run `app('help')` and then write the contents of `CommandResult.stdout` to a file manually in the script. Using **tee** is the far better answer.

**Comment by tleonhardt** [comment]
As long as we are consistent in what gets redirected across all commands I can be happy with it.
