### ISSUE TITLE
Question: escaping special-characters in command

### ISSUE THREAD

**Issue by dannypete** [python-cmd2/cmd2#660]
Hey all,

First of all, thank you for this amazing project. A project of mine has greatly improved thanks to a number of built-in cmd2 features.

I'm looking to add a way to escape special-characters (e.g. `'"[]{}()><|`, etc. which would be interpreted by cmd2 instead of left as characters part of a string) in user-inputted commands. I've spent some time looking through the code and it seems like on location in cmd2's code preventing this is the `parsing.py`'s `shlex_split` wrapper calling `shlex.split` with `posix=False`. 

I'm wondering if there's already a way to add special-character-escaping that I have missed or if this feature would require a change to cmd2's code.

Thanks

**Comment by tleonhardt** [comment]
Hey @dannypete - we are glad to hear that `cmd` has helped improve your project.  

`cmd2` has a custom lexer/parser which has been carefully tweaked to provide a nice shell-like experience that works well in the majority of cases and in what feels like a native fashion on Windows, macOS, or Linux (which is **far** from trivial to achieve).  This custom parser is also optimized to provide good performance so that we can run our 600-ish unit and integration tests in less than 2 seconds on most modern machines.  That cross-OS support and optimized performance does come at a price however.

I'd say that our custom parser in combination with our ``argparse``-based decorators provide a solution that works well for 95% of use cases (give or take).  For those cases where it does't provide the desired functionality, all `do_*` commands get passed an instance of the [Statement](https://github.com/python-cmd2/cmd2/blob/master/cmd2/parsing.py#L76) class by default, which inherits from `str` but has many additional attributes, most importantly in your case the `raw` attribute which gives full access to exactly what the user typed at the input prompt.  You can then parse that in any way you like.  If you are using one of the ``argparse`` decorators for your `do_*` command, then the see the [decorator_example.py]()https://github.com/python-cmd2/cmd2/blob/master/examples/decorator_example.py) example for how to get access to the underlying Statement instance.

**Comment by kmvanbrunt** [comment]
@dannypete You might also look into the [cmd2 hook system](https://cmd2.readthedocs.io/en/latest/hooks.html). These allow you to place custom code at various points of the command being run, including when the command string is parsed. Perhaps you could detect the custom escape sequence then and respond accordingly.

**Comment by kmvanbrunt** [comment]
@dannypete 
For the redirection characters: `> < |`, you can quote them so the parser will leave them alone.
ex: `fake_command ">" other args`

I don't think we do special handling on the other characters you mentioned. So those should just pass right through. Can you provide an example of your syntax so we can provide more detailed help?

**Comment by dannypete** [comment]
I appreciate the prompt help on this.

My specific use case is especially for a multi-line command where a user might paste a paragraph of description text as an argument.

For example:
```
set description "Here is a multi-line description
which might contain quotes (\"), angle brackets (\> or \<),
or even the pipe character (\|)."

```

I am looking to have these characters be escape-able regardless of whether the command is multi-line or not, but I'm expecting the primary use-case of users to be for a multi-line command following the format in the example.

**Comment by kmvanbrunt** [comment]
@dannypete Sorry for the delay in replying.

Since **cmd2's** parser uses **shlex** we have whatever limitations it has. The syntax you are suggesting would require some custom parsing on your part.

As @tleonhardt pointed out, our design decisions work in most cases for a shell-like experience. But certain syntaxes don't produce the tokens a developer hopes for. Our own **py** command has the same problem because Python code doesn't always fit the format of a typical shell command.

See issue #327 for a more complete explanation behind our choice to use **shlex**.

I would also suggest reading the non-POSIX mode [shlex parsing rules](https://docs.python.org/3/library/shlex.html#parsing-rules) to understand what syntaxes won't fit with **cmd2**.
