### ISSUE TITLE
Should terminators affect non-multiline commands?

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#673]
@kotfu Why does the parsing logic not treat terminator characters as literals for non-multiline commands?

**Comment by tleonhardt** [comment]
My guess is that when @kotfu designed and implemented our current parser based on `shlex` which is a replacement for the previous one based on `pyparsing` he strove to maintain strict backward compatibility in parsing logic and that is the way `cmd2` was initially implemented.

That being said, unless there is a good reason to do otherwise, I think it would make the most sense for terminators to only have a special affect for multiline commands and to be treated as simple character literals for non-multiline commands.

**Comment by kotfu** [comment]
@tleonhardt is correct, I implemented the new parser so it exactly matched the old `pyparsing` behavior. I don't feel strongly one way or the other, but here's the argument for always treating terminators as terminators:

In every other language, programming or otherwise where a character other than newline can terminate a command, it always terminates a command. This is the case in SQL, Javascript, C, Python, Perl, Pascal, Ada, csh, bash, etc. In some of these languages, like Python, a semicolon is not required to terminate a command, but if present, it always terminates the command. If someone defines a `cmd2` application that has multi-line commands, and therefore one or more command termination characters (we allow multiple termination characters, any one of them will terminate a command), it seems wise to follow the pattern of every other language design and have the termination character always terminate a command instead of sometimes being part of the command, and sometimes not.

If the developer of a `cmd2` based app sees fit to not allow multi-line commands, that she can choose whether to disable the termination character by setting `cmdapp.terminators = []`. Then the newline becomes the only termination character, and it always terminates commands, thus remaining consistent. She could also choose to set `cmdapp.terminators = [';']`, which would then emulate the behavior of Python and Bash, a newline always terminates a command, and a semicolon also always terminates a command, but is not required to terminate a command.

**Comment by kmvanbrunt** [comment]
I can undertand @kotfu's point.
@tleonhardt Should I just close this question and preserve the existing behavior?

**Comment by tleonhardt** [comment]
@kmvanbrunt Yeah @kotfu made a very strong argument.  I think it is best to preserve current behavior and close this issue.
