### ISSUE TITLE
Minimize public API

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#677]
In preparation for the 1.0.0 release and to align with [Semantic Versioning](https://semver.org/), I think it would be a good idea if we look at the overall `cmd2` public API presented to end users and either explicitly make *internal* functions/methods such by beginning their name with an underscore and/or to do a better job clarifying what we consider the public API to be. 

One way or the other, I think we want to clearly convey the parts of `cmd2` we intend to remain stable within major releases and the parts we don't make any promises about.

**Comment by kotfu** [comment]
It seems to me there are three broad categories of attributes/methods in `cmd2`:

1. Attributes intended for use only within `cmd2.Cmd()`. These should all be changed to start with an underscore. We need to evaluate all attributes/methods and make a determination whether they are for internal use or not. For example, is `path_complete()` for internal use or do we want someone to be able to override it? What about `self.at_continuation_prompt`? There are dozens, maybe hundreds more.

2. The ones that must be immutable. The best way to (try to) enforce this is to put these as arguments to `__init__` and store them in attributes that start with an underscore. This is the standard python notation that these are private and shouldn't be messed with. Terminators, shortcuts, multi-line commands, etc, all fall here. I don't think these need to be made available as "read-only" attributes because the caller already knows them. If the caller wants them available as attributes, they can add them to the instance themselves.

3. Everything else is part of the public API. Every attribute/method that doesn't start with an underscore is public and neither it's signature or name can be changed (with the exception of adding additional keyword arguments) without bumping the major version number. Adding new ones requires bumping the minor version number.
