### ISSUE TITLE
Why does pseudo_raw_input() strip the line?

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#727]
Sometime back in 2017, `pseudo_raw_input()` was changed to strip the line being returned.
This causes some issues, especially with multiline commands with quoted arguments:

<pre>
(Cmd) orate "this is a
>    sentence";
this is a
sentence
</pre>

I would have expected
<pre>
this is a
    sentence
</pre>

I'm also wondering how the newline was supposed to be handled. Going back to the example, did we expect the line break to appear in the sentence? Or did we expect the following?
<pre>
this is a    sentence
</pre>

**Comment by tleonhardt** [comment]
I believe I added that a couple years back when we were working on support for all of the different readline variants on all supported OSes.  I was trying to simplify the previous logic.

In retrospect, I believe this should not have used `.strip()` and should instead of used `.rstrip('\r\n') like so:
```Python
        return line.rstrip('\r\n')
```
