### ISSUE TITLE
Should commands in scripts/transcripts go into history?

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#740]
We now have a flag for `one_cmd` and `one_cmd_plus_hooks` that prevents the command from being saved to history. This is good for cases where one command calls another and you don't want both to show as something the user typed.

Should commands run in text scripts, python scripts, and transcripts be stored in history?
Also what about commands run using the history command or _generate_transcript command?

**Comment by tleonhardt** [comment]
My opinion is that any commands run by a user whether that be directly at the command line or indirectly via scripts, transcript generation, or history run should be be stored in the `cmd2` command history.  

If developers don't want certain commands to be stored in history, then they can add them to the `exclude_from_history` list. 

If a command calls another command, then I would recommend developers to make use of the flag so that those don't get stored in history since that nested command isn't triggered by the user.  But that is really up to the developer at that point.

**Comment by kmvanbrunt** [comment]
Question answered. Closing issue since no changes are required.
