### ISSUE TITLE
Alias and Macro names

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#751]
It has been brought to my attention by another developer that allowing aliases and macros to share names with commands could cause issues with users being unwise. Specifically he said:

> being able to create an alias that overrides/hides a command is bad for usability

Currently we have the following restrictions:

1. Alias cannot share its name with a macro
2. Macro cannot share its name with an alias or a multiline command

When I first wrote aliases, I did prevent them from sharing their name with a command. Then I decided to remove this restriction to be like bash. However, in bash you can still call the original command if you know its path. (e.g. /bin/ls). **cmd2** does not work in the same way since our commands are not executable files somewhere on disk.

I'm OK adding the restriction back, but I would like some consensus on the issue. And I really don't want the answer to be, "add a flag".

@kotfu @tleonhardt @anselor What are your thoughts?

**Comment by anselor** [comment]
There are a few different paths we can go with this. 
My initial thought was to add an flag that a developer can set to enable or disable eclipsing aliases. 

But thinking about it now, I can't really think of a good legitimate case for it to be acceptable to replace a command with an alias to another command. The main acceptable use case for eclipsing a command to with an alias that applies some default parameters to a command. I'm thinking a reasonable balance is maybe restrict the command eclipsing to only in alias-to-self situations.

**Comment by kmvanbrunt** [comment]
I recently had to add an **expand** boolean to the `onecmd` family of functions to make it safe for developers to call the functions without worrying about someone aliasing the commands. If we do add the restriction back, then a bit of code will be simplified by the removal of safeguard checks.

**Comment by tleonhardt** [comment]
I think the best thing to do is provide an experience which is easy for customers to use correctly and hard to use incorrectly.  I can see that allowing aliases and/or macros to override `cmd2` commands could result in some extremely confusing behavior if end users were to do something dumb - basically we are currently given them the opportunity to easily shoot themselves in the foot.

I think it would be a good idea to restring this in one way or another.  I'd be fine with simply disallowing aliases/macros to override command names at all.  I'd also be OK with only allowing them to override an identically named command.

Regardless, we should clearly document the expected behavior.
