### ISSUE TITLE
Passing 'add_to_history' argument to onecmd() causes TypeError

### ISSUE THREAD

**Issue by varshar16** [python-cmd2/cmd2#753]
cmd2 version: 0.9.15
Python version: 3.7.4
OS name and version: Fedora 30

What you did to cause the bug to occur?
Upgrade to cmd2 0.9.15 causes this error.

Include any traceback or error message associated with the bug
CephFS:~/>>> ls
Traceback (most recent call last):
  File "/home/varsha/ceph/build/venv/lib/python3.7/site-packages/cmd2/cmd2.py", line 1807, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
TypeError: onecmd() got an unexpected keyword argument 'add_to_history'
EXCEPTION of type 'TypeError' occurred with message: 'onecmd() got an unexpected keyword argument 'add_to_history''

**Comment by tleonhardt** [comment]
@varshar16 Thanks for reporting this issue.

It looks like from taking a quick look at the [cephfs-shell code](https://github.com/ceph/ceph/blob/65ee02da75929e7616377de003bbb9a16aaf9220/src/tools/cephfs/cephfs-shell#L396), the `CephFSShelll` class overrides the `onecmd` method in order to globally catch errors.

The right fix for this would be to modify that override of `onecmd()` in the ceph-fs code to take an additional keyword-only argument called `add_to_history` which defaults to True and then pass that on to the superclass `onecmd()` method.

Are you affiliated with the Ceph/CephFS project?  I'd recommend submitting a PR or Issue there.

**Comment by varshar16** [comment]
@tleonhardt Thank you for looking at the code and suggesting the solutions, it fixes the error.

I did not understand why it works.
Since superclass ```onecmd()``` method has ```add_to_history``` as default keyword.
In cephfs-shell code, we are no changing any of the default keyword values. Shouldn't the keyword only argument be passed, when they are changed?

**Comment by tleonhardt** [comment]
The problem was that `onecmd_plus_hooks()` calls `onecmd()` and passes it the `add_to_history` keyword-only argument:
```Python3
stop = self.onecmd(statement, add_to_history=add_to_history)
```

`add_to_history` is a relatively new keyword-only argument that got added to `onecmd()` and `onecmd_plus_hooks()`, so when **cephfs-shell** overrode `onemcd()`, they didn't have it expect any keyword arguments and their override was getting called with a keyword argument that it wasn't expecting.

So the easy solution is to just add ``**kwargs` to the override like so:
```Python3
    def onecmd(self, line, **kwargs):
        """
        Global error catcher
        """
        try:
            res = Cmd.onecmd(self, line, **kwargs)
            if self.interactive:
                self.set_prompt()
            return res
        except ConnectionError as e:
            self.perror('***\n{}'.format(e), end='\n', apply_style=True)
        except KeyboardInterrupt:
            self.perror('Command aborted', end='\n', apply_style=True)
        except Exception as e:
            self.perror(e, end='\n', apply_style=True)
            traceback.print_exc(file=sys.stdout)
```

In this use case, `**kwargs` just catches all of the keyword arguments and passes them along to the base class method.  That way, if we add more keyword-only arguments in the future, this code will be resilient to change.

**Comment by varshar16** [comment]
Thank you for the detailed explanation.
