### ISSUE TITLE
Invalid Command name when command starts with same character as a shortcut.

### ISSUE THREAD

**Issue by xNinjaKittyx** [python-cmd2/cmd2#759]
I don't know if `quit` already exists in the library, but I have a command `do_quit` that just exits out of the command line.
And then I use shortcuts to shortcut q -> quit and exit -> quit.

However, doing this results in this error:

```
ValueError: Invalid command name 'quit': cannot start with a shortcut: @@, ?, !, @, q
```

**Comment by tleonhardt** [comment]
So @kmvanbrunt says this is actually a feature ...

If you have a shortcut “q”, then typing  quit would actually run quit with an argument of ”uit”.

There would be no way to run any command that starts with q.

**Comment by xNinjaKittyx** [comment]
Interesting... I feel like as a shortcut that's only useful for a lot of the builtins, but for the original use case of shortcuts it doesn't feel quite as intuitive..

Is there a way to alias commands without having to create new commands that execute the other? There's docs on aliasing within the CLI, but nothing regarding outside the CLI (from what I could tell)

**Comment by kmvanbrunt** [comment]
@xNinjaKittyx 
There is a distinction between shortcuts and aliases that makes shortcuts very convenient. A shortcut does not require a space between it and its arguments. So the following command lines are valid:

- `!ls`
- `?macro`

The parser checks if a command line begins with a shortcut, and if so, splits them as follows:

- `! ls`
- `? macro`

Because of this, there is no way to run your `quit` command directly.

Since `quit` begins with the shortcut `q`,the parser splits it this way: `q uit`
At that point, the parser resolves `q` into `quit` which results in a final command line of

`quit uit`

In your case, the behavior was being masked because your `quit` function probably just ignores the argument `uit` being passed to it.

If your application had another command that started with `q` but wasn't related to `quit`, you would have seen the issue faster. I added the error message to 0.9.16 to prevent this exact problem.

If you still want to type `q` and run `quit`, then you want an alias. For your shortcuts, you will run two commands.
`alias create q quit`
`alias create exit quit`

You can create these at startup in a few ways:
1. Have a startup script that runs your alias creation commands
2. Run `self.runcmds_plus_hooks()` with these commands in a list.

You will see the output of the alias creation when the application starts.

> Alias 'q' created
Alias 'exit' created

If you don't want to see that output, then redirect the commands to /dev/null or your operating system's equivalent. You can also pass `add_to_history=False` to `self.runcmds_plus_hooks()` if you don't want the alias creation commands to be stored in history.

By the way. `cmd2` already has a `do_quit()` method. If ours already does what you need, then you can remove yours.

**Comment by xNinjaKittyx** [comment]
I tried this approach, and it works fine. I also thought about adding another hook to add some special rules, but figured this is a little easier to read (although not ideal in my opinion).

Is there no way to create aliases using an API rather than running commands on the CLI on boot? (startup script or runcmds_plus_hooks())

**Comment by kmvanbrunt** [comment]
@xNinjaKittyx 
You can call `self.do_alias('create q quit')`, but that will print to the screen the alias was created.
You can manually edit the dictionary, but it won't get error checked by the `_alias_create` command.

```Python
self.statement_parser.aliases['q'] = 'quit'
```

There is no Python API wrapping the CLI commands at this time.

**Comment by tleonhardt** [comment]
@xNinjaKittyx If you are looking for something quick and dirty that you can do at code-time rather than on boot, you can do something like this:

```Python3
class QuickApp(cmd2.Cmd):
    def __init__(self):
        super().__init__()

    do_q = do_quit  # now "q" is a synonym for "quit"
```

This just creates a quick and dirty copy of a command with the exact same contents, doctoring, etc.  We document this approach in our [Frontpage README](https://github.com/python-cmd2/cmd2) as well as in several examples such as [first_app.py](https://github.com/python-cmd2/cmd2/blob/master/examples/first_app.py)

**Comment by xNinjaKittyx** [comment]
Cool, I like that one. Thanks everyone.
