### ISSUE TITLE
cmd2 usage within asyncio.get_event_loop().run_until_complete

### ISSUE THREAD

**Issue by adriansev** [python-cmd2/cmd2#764]
Hi! I would like to use cmd2 to create a shell for interactivity with a websocket based service.   
For persistence a websocket must be created within asyncio.get_event_loop().run_until_complete()
see [websockets](https://websockets.readthedocs.io/en/stable/intro.html)
How can i adapt cmd2 to such usage? (note that i am interested only in a shell, not sending commands, as that it is covered) for reference my application is [here](https://github.com/adriansev/jalien_py/blob/master/xjalienfs/alien.py)

**Comment by tleonhardt** [comment]
Hi @adriansev, we have info in the `cmd2` documentation about integrating with [Alternate Event Loops](https://cmd2.readthedocs.io/en/latest/examples/alternate_event_loops.html)

Please see if that answers your question about how you can adapt `cmd2` for use with `ayncio`.

**Comment by adriansev** [comment]
yes, i seen the documentation but it is not clear to me what part from example i am supposed to run within the asyncio.get_event_loop().run_until_complete(). the websocket and related operations are supposed to run within the loop, and my goal is to have a shell like interface where commands are sent to websocket server, and i get back the messages from that server.
moreover : 
```
python3
Python 3.7.4 (default, Jul  9 2019, 16:32:37)
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmd2
>>> app = Cmd2EventBased()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Cmd2EventBased' is not defined
>>>
```

**Comment by adriansev** [comment]
yes, i am just trying to call async functions from cmd2. the "commands" are websocket send messages (async) that then await for recv answer to the server. Is there any way to accommodate this? 
The alternative is to create a global variable (eventually in a namespace to not clash with anything else) were an send_command function would deposit the awaited answer.

**Comment by xNinjaKittyx** [comment]
The way I do it is by creating a cmd2 object as you normally would according to documentation, then within the `do_*` commands, you call `loop.run_until_complete()` on the functions you want to await.

Since if you have a lot of async stuff, it's a little annoying to write a separate async function for every `do_*` function, so I also had my own wrapper that would allow me to use `async def do_*` functions that be wrapped with `run_until_complete()` at runtime, so that cmd2 would work with async functions.

However, this is all assuming that your workflow is to execute command -> await something -> return back to cmd2 prompt and wait for the next input.

If you're goal is to send a command -> return back to prompt -> then alert the cmd prompt when the answer is received, you will probably have to probably mess with the cmd2loop to make it compatible with asyncio.

**Comment by adriansev** [comment]
> However, this is all assuming that your workflow is to execute command -> await something -> return back to cmd2 prompt and wait for the next input.   
It's exactly like that! Thanks a lot!! i will try it out to see how it goes

**Comment by tiolan** [comment]
Hi @tleonhardt, following this guide and the documentation, I was able to run `cmd2` on the `asyncio` event queue with help of `aioconsole`.
It is basically this:
```
    async def run(self):
        while not self.onecmd_plus_hooks(await aic.ainput()):
            pass
```
I can run all my commands.
But what now is lost is the prompt and the welcome message, that I set like this:
```
class Program(cmd2.Cmd):
    def __init__(self):
        cmd2.Cmd.__init__(self)
        self.prompt = "(>>) "
        self.intro = "Welcome"
```
I only have an empty console, that I can use for input.

Here is how I instantiate it:
```
if __name__ == "__main__":
    prog = Program()
    prog.preloop()
    aio.run(prog.run())
    prog.postloop()
```
Any idea what causes this?
When using the built in event loop, it works as expected.
