### ISSUE TITLE
Getting "stty: stdin isn't a terminal" errors when piping input to my app

### ISSUE THREAD

**Issue by kotfu** [python-cmd2/cmd2#803]
I have a ``cmd2`` based app which can accept commands piped via stdin, like so:
```
$ echo some_command | my_app
```

When used in this way, I get the following error:

"stty: stdin isn't a terminal"

I believe this error is caused by a bug in the ``_run_cmdfinalization_hooks()`` method of ``cmd2.Cmd``. If stdout is a tty, and we are not on windows, it runs ``stty sane``, which generates this error message.

**Comment by kotfu** [comment]
Root cause: `stty` operates on stdin. Why do we need this `stty sane` code anyway?

**Comment by tleonhardt** [comment]
@kotfu This code has a check to make sure self.stdout is a tty.  It should also have a check to make sure stdin is a tty.  Actually given what stty does I’m not sure the check on stdout is beneficial.

This code is there because on some OS and terminal combinations, printing binary output to stdout can cause certain characters to interpreted as terminal control characters and stdin settings can get badly messed up.  We could have taken the stance that cmd2 apps have to deal with this situation if they are creating it.  However many users of cmd2 don’t understand terminal intricacies and they viewed it as a bug in cmd2, so we took the proactive stance of fixing things they might have screwed up.

**Comment by kmvanbrunt** [comment]
Oops, this is my fault. I made that change during #655. It previously did check if stdin was a tty. I'll fix it.
