### ISSUE TITLE
Categorizing Dynamic Commands

### ISSUE THREAD

**Issue by KresoDenis** [python-cmd2/cmd2#835]
How to categorize a dynamic command created via

`setattr(CommandsInLoop, 'do_{}'.format(command), functools.partialmethod(CommandsInLoop.send_text, text=command))`

in dynamic example

running categorize function from cmd2 dont work since i guess it was not mean to be used this way.

Any other alternative way. There seems to be nothing in documentation.

**Comment by KresoDenis** [comment]
P.S. I found solution in using functools.partial instead of functools.partialmethod
where i could do 

    sarma = functools.partial(CommandsInLoop.send_text, text=command)
    setattr(sarma, 'help_category', 'somecategory')
    setattr(CommandsInLoop, 'do_{}'.format(command), sarma)

But im guessing there should be something more streamlined than this.

**Comment by tleonhardt** [comment]
@KresoDenis 
I think you might jus need to pass your `sarma` variable to `categorize()`

Some of our developers do use dynamic commands but we didn't want to add a particular implementation to our code base for easily doing that since there are infinite ways to do that and we didn't want to impose a single way.  We believe we provide all the functions necessary already.

It really comes down to your needs ...
1. Are you creating functions dynamically?
2. Do you have existing functions in other files that you add once?
3. Are your functions loaded and unloaded as part of a plugin at an unknown time by the user?
4. Are you adding the functions to the CLI class or an instance?

Once you answer those questions, the solution is generally a Pythonic one and not so much `cmd2` specific.

@kmvanbrunt Do you have any further comments and/or suggestions?

**Comment by kmvanbrunt** [comment]
@tleonhardt I agree with your comment

**Comment by KresoDenis** [comment]
I just tried. Categorize does not work on partialmethod in cmd2 dynamic example. It does only work when using partial instead of partialmethod with settattr or categorize. Just wondered whats the proper way for partialmethod since that is default in examples. But i have no blockers. Just wanted to know how you solved it with partialmethods.

**Comment by kmvanbrunt** [comment]
It looks like Python is not preserving the help category attribute when it binds the partial method object to the `CommandsInLoop` instance.

I've rewritten the example to add commands in the instance's `__init__()` method and this works with categories. See PR #840.

**Comment by kmvanbrunt** [comment]
@KresoDenis The example has been merged into master. Let us know if this is works out for you.

**Comment by KresoDenis** [comment]
Sure thing. Example PR moved from partialmethod to partial. Same as i did. I think that is the reason why it works. Even without moving it to __init__() partial should work.

It Works out for me. Adding categorization in example of dynamic ones will help others. If that means using just partial in example instead of partialmethod. Im ok with that. Thanks.
