### ISSUE TITLE
Does the edit command provide value?

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#865]
I did a quick audit of the built-in `cmd2` commands with an eye towards whether or not they should exist in a generic framework for interactive command-line applications.  Nearly all of the commands feel like they provide specific value.

The one I am questioning is **edit**.  Since we can run arbitrary shell commands, it is trivial to open any editor on the user's path to edit any file on their path so I don't necessarily see a value other than for users who don't know the name of an editor.  Maybe that is worthwhile.  Maybe not.  I would like to solicit other opinions in regards to whether or not we should leave this in as a built-in command.

Also, if we do decide to keep the **edit** command it currently allows us to call the edit command without a file path.  However if we open an editor in this fashion, we can't save our edits.  That doesn't seem to be useful at all.  If we do leave **edit** in, should we make the `file_path` argument required?

@kmvanbrunt @kotfu @anselor 
If any of you have an opinion on this, please state it.  All other users of ``cmd2`` are more than welcome to chime in as well.

P.S.  I am also slightly questioning the value of the **py** command given that we have an optional **ipy** and a **run_pyscript** for running Python scripts.  It does seem like it provides some value for very uncommon use cases.  But I'm not sure it makes sense to leave it in generically to satisfy those rare use cases.  So I would welcome opinions in regards to the usefulness (or lack thereof) of **py** in addition to **edit**.

**Comment by kmvanbrunt** [comment]
I'm OK removing it since **edit** is a name that is commonly overloaded. I actually changed `do_history()` to no longer rely on `do_edit()` for this reason.

Since we have good shell command support, a user can always type `!vi file`

**Comment by kotfu** [comment]
I don't agree with this part of the question:

> Also, if we do decide to keep the edit command it currently allows us to call the edit command without a file path. However if we open an editor in this fashion, we can't save our edits. That doesn't seem to be useful at all. If we do leave edit in, should we make the file_path argument required?

I have the `EDITOR` environment variable set to `emacs`. When I type `edit` with no file path from within a `cmd2` application, it opens emacs with no file loaded. From there I can issue a command to open files, make changes, save them, etc. and it all works fine.

Setting my quibble with this portion of the question aside, I'm not sure what we are solving for by removing the `edit` command. We have already allow and have documented how developers who want to remove (or hide) built-in commands can do so (https://cmd2.readthedocs.io/en/latest/features/disable_commands.html#disabling-commands). As currently implemented, it's also trivial for a developer to create their own `do_edit` command which does something else, and re-implement the "open-a-text-editor-command" as `do_foobar` with 3-4 lines of code.

Since there are many workarounds available for developers to do what they want with the built-in `edit` command, and since we already have it and have had it for a long time, I think we should leave it. However, I don't feel super strongly about this, if other believe we have a good reason to delete the `edit` command, I can be persuaded.

**Comment by tleonhardt** [comment]
@kotfu Excellent point about calling the `edit` command without a filename still being quite useful.

I don't feel strongly that `edit` should be removed.  I was just trying to take a look at all of the built-ins with fresh eyes to see if there was anything which felt like it didn't belong.

**Comment by tleonhardt** [comment]
I'm going to close this.  It sounds like `edit` is used and provides some value.
