### ISSUE TITLE
command names with dashes

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#907]
Currently `cmd2` cannot support command names with dashes `-` because command names are based on Python method names, so underscores `_` are fair game but dashes are not.  However, some coding conventions prefer or require command names with dashes separating words.  It would be nice if `cmd2` had a mechanism to support command names with dashes.

From some preliminary conversations with @kmvanbrunt we can envision two radically different ways of supporting this:
1. Add an application-wide boolean flag called something like `dash_mode`
    * This flag would enforce one convention in all command names (either underscores or dashes) and if True would replace all underscores with dashes, including for built-in commands
1. Add a `@command` decorator which accepts a command-name string
    * We would need to maintain a dictionary mapping command names to methods

The former flag approach is almost definitely easier to implement and maintain, particularly when it comes to parsing commands, aliases, macros, etc.  The latter decorator approach is more flexible but potentially much more unwieldy and more of a departure from `cmd`.

**Comment by kotfu** [comment]
I like the idea of supporting dashes in command names. I agree it's gonna be tricky to find a clean method of implementing it, and it feels like its gonna be a lot of work.

Of the two suggestions above, I like the decorator method the best. If you don't use our special decorator on your command, then everything works like it previously has. If you use our special decorators like so:
```
@command_name("speed-up")
def make_it_fast(self, cmdline: cmd2.Statement):
    ...

@command_help("speed-up")
def make_it_fast_help(self):
    ...
```

then you can name your command methods and help methods whatever you want.

**Comment by anselor** [comment]
I really like this idea. It's elegant and opens up options.

**Comment by kmvanbrunt** [comment]
Developers will have to remember to manually decorate some cmd2 built-ins (run_script, run_pyscript) for a consistent command name convention. One issue that could arise is if any of our subcommand names have an underscore. None currently do, but would a subcommand named in this way violate the coding convention we're trying to support?

**Comment by kmvanbrunt** [comment]
Also what about help_* and complete_* functions? Will those need a decorator, too?

**Comment by kotfu** [comment]
I didn't think about the built-in commands, and we certainly would want a way for a developer to have the built-in commands use dashes instead of underscores. How could I, as a developer using the cmd2 library, even decorate a built-in command?

It's almost like we would have to have a private internal data structure that maps "input command names" to "python command functions". The decorator would be one way to add entries to that map, which could be stored as a dictionary. Maybe we would have to provide another way to add/modify entries in that dictionary. So a developer could do something like:

```
def MyApp(cmd2.Cmd):

def __init__(self):
    super().__init__()
    self.rename_command("run_pyscript", "run-pyscript")
```

The `rename_command()` method would:
- look for an key "run_pyscript" in the dictionary, which would have as it's value the "do_run_pyscript" method
- if "run_pyscript" is not found in the dictionary, we know the method is "do_run_pyscript"
- create a new key "run-pyscript" in the dictionary with a value containing the "do_run_pyscript" method
- delete the "run_pyscript" key and value from the dictionary (if it was there)

Then we could also create a method called `dashify_builtins()` which would call `rename_command()` for each built-in command.

You notice I'm avoiding the subcommand issue, because I have no good ideas there 🤷‍♂ .

**Comment by kotfu** [comment]
And yes the help_* and complete_* functions would need their respective decorators and internal maps. Maybe the `rename_command()` thing should update all three maps.

**Comment by kotfu** [comment]
Or maybe instead of this:

```
@command_name("speed-up")
def make_it_fast(self, cmdline: cmd2.Statement):
    ...

@command_help("speed-up")
def make_it_fast_help(self):
    ...

@command_complete"speed-up")
def make_it_fast_completer(self, .....):
    ...
```
You could do:
```
@command("speed-up", help=self.make_it_fast_help, completer=self.make_it_fast_completer)
def make_it_fast(self, cmdline: cmd2.Statement):
    ...

def make_it_fast_help(self):
    ...

def make_it_fast_completer(self, .....):
    ...
```

**Comment by kotfu** [comment]
I've started an experiment to see if we can make this work. `dashes` branch.

**Comment by kotfu** [comment]
Barebones implementation of `self.rename_command()` working for both built-in and custom commands, i.e. from "speed_up" to "speed-up". All the hard work, i.e. completion, enabling/disabling commands and categories, etc. still remains. Still don't know if this approach is a viable solution to the problem or not.

**Comment by kotfu** [comment]
More investigation and progress. Hidden and disabled commands don't look like they will be a problem. We have some checking in and for shortcuts and aliases, which will need to be expanded to account for our "maps". ``_help_menu()`` and the things it calls will need a bit of refactoring. Still need to investigate completer methods.

**Comment by kotfu** [comment]
I have completer methods working now in the `dashes` branch. At this point I believe that:

- the basic idea of having a map to redirect command names to method names works
- we have a working implementation of a `rename_command()` method which demonstrates it works
- run `examples/cmds_with_dashes.py` in the `dashes` branch to test it out
- this basic implementation can easily be extended with decorators and other convenience methods like `dashify_builtin_commands()`

There is still plenty of work to do to finish this off, including:

- updating the methods which enable/disable commands and categories of commands
- reworking/refactoring the `_help_menu()` function and all the children functions it calls
- write the documentation for this functionality
- a bunch of other little stuff that's noted in `dashes-todo.txt` in the branch

Before I continue with the rest of the work, I'd like some preliminary feedback from others if this is a good idea and worth completing the work required to make a new pull request.

**Comment by kmvanbrunt** [comment]
Of the two approaches @tleonhardt laid out when he created this issue, the first approach regarding a `dash_mode` flag was mine.

I prefer this method over a decorator because it has a singular focus and requires little of the developer to remove dashes from commands/subcommands. Just set a flag and you're done. A decorator-based approach requires decorating every command that has an underscore. I also am unsure the use case for renaming command functions outside of removing dashes. Perhaps other developers will like this feature though.

That said, if we do stick with the decorator approach, we should include a `dashify_commands()` to dashify all commands and not just the built-in ones. That way a developer won't be required to decorate anything and this method can leverage the work you've already done with the dictionaries. I believe this brings the simplicity goal from the flag approach into the decorator approach.

One problem common to both approaches is updating the `argparse` parsers tied to each function. We need to update the `prog` member so usage statements match the new command name. This can be done with `_set_parser_prog()` in `decorators.py`. We also need a function to dashify any subcommands. I don't think that's too difficult given what we know about the layout of parsers.

@kotfu Overall I appreciate the work you've put into this. I also recognize the decorator approach offers far more flexibility that my approach. So that's a major plus.

**Comment by kmvanbrunt** [comment]
Code to dashify subcommands and their help text
```Python
def dashify_subcommands(parser: argparse.ArgumentParser):
    """
    Recursively dashify subcommand names of a parser and all of its subparsers

    :param parser: the parser being edited
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            # Dashify subcommand names
            for choice in list(action.choices.keys()):
                if '_' in choice:
                    new_name = choice.replace('_', '-')
                    action.choices[new_name] = action.choices.pop(choice)

            # Dashify any metavars which match the dest field. This fixes help text.
            for choice in action._choices_actions:
                if choice.dest == choice.metavar and '_' in choice.metavar:
                    new_name = choice.dest.replace('_', '-')
                    choice.metavar = new_name

            # Dashify subcommands of this subcommand
            for sub_cmd_parser in action.choices.values():
                dashify_subcommands(sub_cmd_parser)

            # We can break since argparse only allows 1 group of subcommands per level
            break
```

**Comment by kotfu** [comment]
I'm not convinced we need the decorators either. I agree that the only use case I can envision for all of this right now is to have dashes instead of underscores in command names. I'd be perfectly happy if there was just a `dashify_commands()` function you could call in `__init__` that would find all commands/sub commands on the object and turn underscores to dashes.

The currently proposed implementation would offer enough flexibility that in the future, if some other use case emerged which benefitted from commands containing characters not allowed in method names, we could offer a decorator without having to rework the underlying infrastructure.

**Comment by kotfu** [comment]
Also note that if we provide a core `rename_command()` method, which our `dashify_commands()` would call for each command containing an underscore, then third party developers could easily write their own decorator to call `rename_command()` if they want to do it piecemeal instead of using `dashify_commands()`.

**Comment by kmvanbrunt** [comment]
I like the `rename_command()` idea. That's the function which will need to call `_set_parser_prog()` if the command's function has an argparse parser.

Should we move `_set_parser_prog()` to utils.py?

**Comment by kmvanbrunt** [comment]
I can see weird edge cases dashifying subcommands.

1. Two subcommands named `do_stuff` and `do-stuff`. We can't rename `do_stuff` to `do-stuff` without overwriting an existing subcommand.

2. A subcommand called `do_stuff` with an `argparse` subcommand alias named `do-stuff`. That gets weird because the metavar for the subcommand is: `do_stuff (do-stuff)`. We'd have to delete the alias, rename the subcommand with a dash, and rewrite metavar.

Are these cases too stupidly obscure to care? Would we blame the developer for calling `dashify_commands()` in this situation?

**Comment by kmvanbrunt** [comment]
New version of `dashify_commands()` handles case where dashified name causes a conflict. It also preserves order of choices dictionary, which is relied upon by `_set_parser_prog()`.

```Python
def dashify_subcommands(parser: argparse.ArgumentParser):
    """
    Recursively replace underscores with dashes in subcommands and aliases of a parser and all of its subparsers.

    :param parser: the parser being edited
    :raises: RuntimeError if a dashified name matches an existing subcommand or alias of parser.
             (e.g. Don't use this on a command with subcommands called do_stuff and do-stuff)
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            # Fix the help text that displays when a command lists its subcommands (e.g. command -h)
            for choice in action._choices_actions:
                choice.dest = choice.dest.replace('_', '-')
                choice.metavar = choice.metavar.replace('_', '-')

            # Dashify subcommands and aliases. We want to preserve the order of the original choices dictionary
            # since other code in cmd2 relies on subcommand names appearing in the keys list before their aliases.
            # To keep the code simple we will delete and reinsert every key, whether or not they have underscores.
            for name in list(action.choices.keys()):
                sub_cmd_parser = action.choices[name]
                del action.choices[name]

                new_name = name.replace('_', '-')

                if new_name in action.choices:
                    raise RuntimeError("Cannot dashify `{}` since `{}` already exists in this parser".format(name, new_name))
                action.choices[new_name] = sub_cmd_parser

                # Dashify subcommands of this subcommand
                dashify_subcommands(sub_cmd_parser)

            # We can break since argparse only allows 1 group of subcommands per level
            break
```

**Comment by kmvanbrunt** [comment]
@kotfu I just posted a new version of `dashify_subcommands()`.

The code to use it will need to look something like the following:

```Python
def dashify_command(name):
    new_name = name,replace('_', '-')
    rename_command(name, new_name)

def rename_command(name, new_name):
    # Do the cmd2 renaming stuff here
    ...

    # Update argparse data to reflect the new name
    func = self.cmd_func(new_name)
    argparser = getattr(func, constants.CMD_ATTR_ARGPARSER, None)

    if argparser is not None:
        dashify_subcommands(argparser)
        _set_parser_prog(argparser, new_name)
```

Should `dashify_subcommands()` and `_set_parser_prog()` be moved to utils.py? Should `_set_parser_prog()` become public?

When you are ready, I can write unit tests for `dashify_subcommands()`.

**Comment by kmvanbrunt** [comment]
@kotfu I found one other area that needs to be changed to support renaming.
In `decorators.py`, there are three instance in which we call:

`cmd2_app.statement_parser.get_command_arg_list(command_name,`

The value for `command_name` is set the moment a command function is wrapped. We need to update it whenever a command is renamed.

**Comment by tleonhardt** [comment]
Where are we with this issue?  I know a lot of code has been implemented.  Are there decisions that need to be made?  Code that needs to be tested?

**Comment by tleonhardt** [comment]
Since no work has been done on this issue in almost 11 months and a ton of changes have happened since, I'm going to resolve this issue and delete the branch.

This would be a nice-to-have feature, but I think it would require some rethinking for how it will work with CommandSets and the like.

**Comment by tewhalen** [comment]
I'm experimenting with something similar - I'd like to have commands that start with a slash. I'm taking the approach of overriding some standard functions and using a dict to map substititions between commands and do_* methods so I can have a method named "do_slash_travel" and have that interpreted as "/travel".

```
class TryApp(cmd2.Cmd):
    commandname_map = {"slash_": "/"}

    def get_all_commands(self) -> List[str]:
        """Return a list of all commands"""
        return [
            self._funcname_cmd_name(name)
            for name in self.get_names()
            if name.startswith(constants.COMMAND_FUNC_PREFIX)
            and callable(getattr(self, name))
        ]

    def _funcname_cmd_name(self, function_name: str) -> str:
        """Get the command name associated with a given function name"""
        prefix_len = len(constants.COMMAND_FUNC_PREFIX)
        cmd_name = function_name[prefix_len:]
        for k, v in self.commandname_map.items():
            cmd_name = cmd_name.replace(k, v)
        return cmd_name

    def _cmd_func_name(self, command: str) -> str:
        """Get the method name associated with a given command.
        :param command: command to look up method name which implements it
        :return: method name which implements the given command
        """
        func_name = constants.COMMAND_FUNC_PREFIX + command
        for k, v in self.commandname_map.items():
            func_name = func_name.replace(v, k)
        return func_name if callable(getattr(self, func_name, None)) else ""



```
