### ISSUE TITLE
Cmd2 usage query

### ISSUE THREAD

**Issue by Twink-Polar** [python-cmd2/cmd2#912]
Hi. Is it possible via cmd2 usage to create a command structure whereby you have the initial prompt “(Menu)>”. You have subcommands (e.g. Configure, Status) so when you type their name you move “into” that sub command i.e “(Menu\Configure)>”. At this point you’d have a list of commands that are specific to “Configure” available to you. Is this possible?

**Comment by kmvanbrunt** [comment]
When in Configure, do you still want the top-level commands available, too?

**Comment by Twink-Polar** [comment]
Apart from a way of getting back to the top level, no I wouldn’t need the top level commands.

**Comment by tleonhardt** [comment]
@Twink-Polar Most of the time, we intentionally steer clear of menu-driven command line applications because from our experience they really make customers/users unhappy; so `cmd2` doesn't have features to explicitly support these. 

We strongly prefer to use a flat command structure where commands can have sub-commands as defined by `argparse` and use of the `@cmd2.with_argparser` decorator.  `cmd2` has excellent support out-of-the box for this scenario.

Additionally, there is definitely the need for stateful applications where different commands are available say once connected to a persistent network resource of some kind (database, server, etc.).  For that `cmd2` provides the ability to dynamically enable and disable commands.  I'd recommend taking a look at the `cmd2` documentation for how to [Disable A Category of Commands](https://cmd2.readthedocs.io/en/latest/features/disable_commands.html#disable-a-category-of-commands).

**Comment by kmvanbrunt** [comment]
You can do this one of 2 ways with features already built into cmd2.
1. Implement all configure commands as subcommands of configure using argparse. Then you don't need to enter a submode to use these commands. You'd just type: `category <command>'. These subcommands also would tab complete.

2. Categorize your commands with the `@with_category` decorator and then enable/disable the as you enter certain modes. See [help_categories.py](https://github.com/python-cmd2/cmd2/blob/master/examples/help_categories.py) for an example of this.

Something like this:
```Python
from cmd2 import COMMAND_NAME

# Command category names
CONFIGURE_COMMANDS = "Configure Commands"

# Message which prints when a user tries to use a disabled command
DISABLED_MESSAGE =  "{} is not available while {} commands are disabled".format(COMMAND_NAME, self.current_mode)

def __init__(self):
    """Your CLI initializer"""
    self.current_mode = None

    # Disable all command categories that depend on mode
    self.disable(CONFIGURE_COMMANDS, DISABLED_MESSAGE)

@with_category(CONFIGURE_COMMANDS)
def do_foo(self, args):
    """This command is only available with in Configure mode"""
    ...

def do_configure(self, args):
    self.toggle_mode(CONFIGURE_COMMANDS, "Menu\Configure>")

def toggle_mode(self, new_mode, new_prompt):
    """Enable commands for the new mode and update the prompt"""
    if new_mode == self.current_mode:
        return

    if self.current_mode is not None:
        self.disable_category(self.current_mode, DISABLED_MESSAGE)
    self.enable_category(new_mode)
    self.current_mode = new_mode
    self.prompt = new_prompt
```

**Comment by Twink-Polar** [comment]
@tleonhardt thank you for your reply. I see where your coming from. I’ll try rationalising my commands and sub commands.

**Comment by Twink-Polar** [comment]
@kmvanbrunt thank you. I’ll give the code snippet a spin but I’ll also work on implementing option 1.

**Comment by tleonhardt** [comment]
@Twink-Polar Since you have a path forward, I'm going to close this issue.  Please feel free to create a new one if you run into trouble and/or if our documentation is lacking.  Good luck!
