### ISSUE TITLE
Asynchronous query

### ISSUE THREAD

**Issue by Twink-Polar** [python-cmd2/cmd2#920]
Part of my cmd2 app I start a couple of system services e.g sshd and docker. In addition I want to monitor those services to make sure they stay “active”, if for some reason they fail I want to alert the cmd2 app. 

Additionally I want to have returned the user back to the cmd2 app prompt so they can run other commands. 

This has led me down the path of needing to run this aspect asynchronous to allow the cmd2 to carry on. 

Is this possible?

**Comment by tleonhardt** [comment]
@Twink-Polar Yes absolutely this is possible - you are far from the first user to need this capability.

Please see the [Prompt - Asynchronous Feedback](https://cmd2.readthedocs.io/en/latest/features/prompt.html#asynchronous-feedback) section of the user manual.  Which come to think of it, perhaps we should move to its own section since some of the ways of doing it really aren't related to the prompt.

Also see the [async_printing.py](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) example for a concrete demonstration for how to use these features.

**Comment by Twink-Polar** [comment]
Brilliant, thank you. I’ll explore those options.
