### ISSUE TITLE
What is the proper way to upate the prompt after every command?

### ISSUE THREAD

**Issue by jkeen871** [python-cmd2/cmd2#948]
I want to update the prompt with a status value from  a local database each time the user presses enter.

for example :

appstatus[OK]:
or 
appstatus[FAILED]:

Thanks,

**Comment by tleonhardt** [comment]
HI @jkeen871, various different approach would work.  But one easy approach, I would recommend you take a look at the [python_scripting.py](https://github.com/python-cmd2/cmd2/blob/master/examples/python_scripting.py#L39-L53) example.

**Comment by kmvanbrunt** [comment]
@jkeen871 If you choose the simple option of just updating the prompt when a user presses Enter, you will want to use a **command finalization hook** instead of a **post command hook**. The difference is that a **command finalization hook** will run even if the user hits Enter on a blank command line.

```Python
class App(cmd2.Cmd):
    def __init__(self, *args, *kwargs):
        super().__init__(*args, **kwargs)
        self.register_cmdfinalization_hook(self._update_prompt_hook)

    def _update_prompt_hook(self, data: cmd2.plugin.CommandFinalizationData) -> cmd2.plugin.CommandFinalizationData:
        # Add code to generate the new prompt value
        self.prompt = new_val
        return data
```

As @tleonhardt mentioned, **cmd2** also has the ability to update the prompt even while the user is at the command line. It works best if the prompt doesn't change in size. If it does, then the user's text at the command line will get shifted and it won't look very seamless. So just leave space for the largest app status that can appear.

[async_printing.py](https://github.com/python-cmd2/cmd2/blob/master/examples/async_printing.py) demonstrates how to dynamically update the prompt as well as how to print alerts to the user without disturbing what the user is typing. The example was written in a tutorial format. Just read from top to bottom and it will show you the best practices for this functionality.

**Comment by tleonhardt** [comment]
@jkeen871 Since your question has been answered I am going to close this issue.
