### ISSUE TITLE
Allow CommandSets to have their own user-settable settings

### ISSUE THREAD

**Issue by kmvanbrunt** [python-cmd2/cmd2#965]
Currently `do_set` is limited to attributes of `cmd2.Cmd` classes. Make it possible for attributes of `CommandSet` to also be settable.

**Comment by anselor** [comment]
Started some work on the cmdset_settables branch which allows additional Settables to be added to cmd2. The issue is tracking settables added by a CommandSet to make sure they're unregistered when the CommandSet is unregistered. 

Probably going to take a new direction and have each CommandSet manage its own dictionary of settables. Cmd2 will search first the cmd2 dictionary, then the CommandSets. This way settables always have a lifetime linked to the CommandSet it's registered in. This does add the problem of potential duplicate names - which will be something the developer will have to be mindful of.

**Comment by tleonhardt** [comment]
@anselor Is this something you are still working on?  Do you believe this needs to get in the 2.0 release?  Or can it come afterwards?

**Comment by anselor** [comment]
@tleonhardt @kmvanbrunt 

This is where I'm at now. I think this should work pretty well. Here's the gist of it:

- Each CommandSet has its own settables. 
- Renamed attribute `settables` to `_settables` and added a new `settables` property that combines cmd2's `_settables` with the ones from all CommandSets
- New cmd2.Cmd attribute `always_prefix_settables` will prepend all settables from CommandSets with a settable_prefix provided by each CommandSet

https://github.com/python-cmd2/cmd2/compare/cmdset_settables

If we're happy with this general approach I'll go ahead and add unit tests to verify the behavior.

**Comment by tleonhardt** [comment]
@anselor I took a quick look at the code on your branch and overall it looks good and the approach seems solid.

Specific recommendations I have are:
- Consider making `self._installed_command_sets` a `set` instead of a `list` so that testing membership is O(1) instead of O(n)
- Run `flake8`, `black`, and `isort` to fix various warnings/errors
